import { FormEvent, useEffect, useMemo, useState } from 'react'
import { BadgeCheck, Banknote, Bell, Building2, CalendarDays, CheckCircle2, Clock3, Copy, CreditCard, FileText, KeyRound, LogOut, Mail, MapPin, Pencil, Save, ShieldCheck, Sparkles, UserRound, Zap } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { CustomerProfile, CustomerSubscription, Entitlement, NotificationOutbox, SalesOrder, SalesPlan, SalesSettings } from '../types'

type Method = 'bank_transfer' | 'paypal' | 'card' | 'invoice'
type ProfileForm = { full_name: string; phone: string; company: string; tax_id: string; company_number: string; address: string; city: string; country: string }
const emptyProfile: ProfileForm = { full_name: '', phone: '', company: '', tax_id: '', company_number: '', address: '', city: '', country: 'Serbia' }

export function BillingPage({ email, onAccessChanged, onSignOut }: { email: string; onAccessChanged: () => Promise<void>; onSignOut: () => Promise<void> }) {
  const [plans,setPlans]=useState<SalesPlan[]>([]), [subscriptions,setSubscriptions]=useState<CustomerSubscription[]>([]), [orders,setOrders]=useState<SalesOrder[]>([])
  const [settings,setSettings]=useState<SalesSettings|null>(null), [profile,setProfile]=useState<CustomerProfile|null>(null), [entitlement,setEntitlement]=useState<Entitlement|null>(null)
  const [profileForm,setProfileForm]=useState<ProfileForm>(emptyProfile), [notifications,setNotifications]=useState<NotificationOutbox[]>([])
  const [interval,setInterval]=useState<'monthly'|'yearly'>('monthly'), [license,setLicense]=useState(''), [selectedPlan,setSelectedPlan]=useState<SalesPlan|null>(null), [method,setMethod]=useState<Method>('bank_transfer')
  const [note,setNote]=useState(''), [working,setWorking]=useState(false), [message,setMessage]=useState(''), [createdOrder,setCreatedOrder]=useState<SalesOrder|null>(null), [showProfile,setShowProfile]=useState(false)

  useEffect(()=>{void load()},[])
  const visiblePlans=useMemo(()=>plans.filter(p=>p.billing_interval===interval),[plans,interval])
  const current=useMemo(()=>subscriptions.find(s=>['active','trialing'].includes(s.status)&&(!s.expires_at||new Date(s.expires_at).getTime()>Date.now())),[subscriptions])
  const pendingOrders=useMemo(()=>orders.filter(o=>o.status==='pending'),[orders])
  const usagePercent=entitlement?.generation_limit&&entitlement.generation_limit>0?Math.min(100,Math.round(((entitlement.generated_this_month||0)/entitlement.generation_limit)*100)):0
  const daysLeft=current?.expires_at?Math.max(0,Math.ceil((new Date(current.expires_at).getTime()-Date.now())/86400000)):null

  async function load(){
    await supabase.rpc('sync_account_notifications')
    const [a,b,c,d,e,f,g]=await Promise.all([
      supabase.from('sales_plans').select('*').eq('active',true).eq('public',true).order('sort_order'),
      supabase.from('customer_subscriptions').select('*, sales_plans(*)').order('created_at',{ascending:false}),
      supabase.from('sales_orders').select('*, sales_plans(*)').order('created_at',{ascending:false}).limit(20),
      supabase.from('sales_settings').select('*').eq('id',1).maybeSingle(),
      supabase.from('customer_profiles').select('*').maybeSingle(),
      supabase.rpc('current_entitlement'),
      supabase.from('notification_outbox').select('*').eq('visible_in_app',true).order('created_at',{ascending:false}).limit(12),
    ])
    setPlans((a.data||[]) as SalesPlan[]);setSubscriptions((b.data||[]) as CustomerSubscription[]);setOrders((c.data||[]) as SalesOrder[]);setSettings((d.data||null) as SalesSettings|null)
    const p=(e.data||null) as CustomerProfile|null;setProfile(p);setProfileForm(p?{full_name:p.full_name||'',phone:p.phone||'',company:p.billing_company||p.company||'',tax_id:p.billing_tax_id||'',company_number:p.billing_company_number||'',address:p.billing_address||'',city:p.billing_city||'',country:p.billing_country||'Serbia'}:emptyProfile)
    setEntitlement((f.data||null) as Entitlement|null);setNotifications((g.data||[]) as NotificationOutbox[])
  }
  async function startTrial(){setWorking(true);setMessage('');const{error}=await supabase.rpc('request_trial');if(error)setMessage(humanError(error.message));else{setMessage('Probni period je aktiviran. Autopilot je otključan.');await load();await onAccessChanged()}setWorking(false)}
  async function redeem(){if(!license.trim()){setMessage('Unesi aktivacioni kod.');return}setWorking(true);setMessage('');const{error}=await supabase.rpc('redeem_license_code',{p_code:license.trim()});if(error)setMessage(humanError(error.message));else{setLicense('');setMessage('Licenca je aktivirana. Paket je odmah otključan.');await load();await onAccessChanged()}setWorking(false)}
  async function saveProfile(event?:FormEvent){event?.preventDefault();setWorking(true);setMessage('');const{error}=await supabase.rpc('save_billing_profile',{p_full_name:profileForm.full_name||null,p_phone:profileForm.phone||null,p_company:profileForm.company||null,p_tax_id:profileForm.tax_id||null,p_company_number:profileForm.company_number||null,p_address:profileForm.address||null,p_city:profileForm.city||null,p_country:profileForm.country||'Serbia'});if(error)setMessage(humanError(error.message));else{setMessage('Podaci za kupovinu i fakturu su sačuvani.');setShowProfile(false);await load()}setWorking(false)}
  async function createOrder(){if(!selectedPlan)return;if((method==='invoice'||method==='bank_transfer')&&!profileForm.full_name.trim()){setShowProfile(true);setMessage('Pre narudžbine upiši ime / kontakt za uplatu.');return}setWorking(true);setMessage('');const{error:profileError}=await supabase.rpc('save_billing_profile',{p_full_name:profileForm.full_name||null,p_phone:profileForm.phone||null,p_company:profileForm.company||null,p_tax_id:profileForm.tax_id||null,p_company_number:profileForm.company_number||null,p_address:profileForm.address||null,p_city:profileForm.city||null,p_country:profileForm.country||'Serbia'});if(profileError){setMessage(humanError(profileError.message));setWorking(false);return}const{data,error}=await supabase.rpc('create_sales_order',{p_plan_id:selectedPlan.id,p_payment_method:method,p_customer_note:note||null});if(error)setMessage(humanError(error.message));else{const order=data as SalesOrder;setCreatedOrder(order);setMessage(`Narudžbina ${order.order_number} je kreirana.`);setNote('');await load();if(method==='paypal'&&settings?.paypal_url)window.open(settings.paypal_url,'_blank','noopener,noreferrer')}setWorking(false)}
  async function markNotificationRead(row:NotificationOutbox){if(row.read_at)return;const at=new Date().toISOString();await supabase.from('notification_outbox').update({read_at:at}).eq('id',row.id);setNotifications(list=>list.map(x=>x.id===row.id?{...x,read_at:at}:x))}
  function copy(v:string){navigator.clipboard.writeText(v).then(()=>setMessage('Kopirano.')).catch(()=>setMessage('Kopiranje nije dozvoljeno u browseru.'))}

  const methods:{key:Method;label:string;enabled:boolean;icon:typeof Banknote}[]=[{key:'bank_transfer',label:'Uplata na račun',enabled:settings?.allow_bank_transfer??true,icon:Banknote},{key:'invoice',label:'Predračun / faktura',enabled:settings?.allow_invoice??true,icon:FileText},{key:'paypal',label:'PayPal',enabled:Boolean(settings?.allow_paypal&&settings?.paypal_url),icon:CreditCard},{key:'card',label:'Kartica',enabled:Boolean(settings?.allow_card),icon:CreditCard}]
  const bankText=[settings?.legal_name||settings?.company_name,settings?.bank_name,settings?.bank_account?`Račun: ${settings.bank_account}`:'',settings?.payment_model?`Model: ${settings.payment_model}`:'',settings?.bank_instructions].filter(Boolean).join('\n')

  return <div className="billing-page billing-v2"><div className="billing-topbar"><div><strong>Restaurant Autopilot</strong><span>{email}</span></div><div className="billing-top-actions">{current&&<button className="primary" onClick={onAccessChanged}><Sparkles size={15}/> Uđi u Autopilot</button>}<button className="secondary" onClick={onSignOut}><LogOut size={15}/> Odjavi se</button></div></div>
    {current?<section className="account-hero"><div className="account-plan-mark"><BadgeCheck size={30}/></div><div className="account-plan-copy"><p className="eyebrow">PAKET AKTIVAN</p><h1>{current.sales_plans?.name||entitlement?.plan_name||'Restaurant Autopilot'}</h1><p>{current.status==='trialing'?'Probni period radi sa pravim funkcijama.':'Licenca je aktivna. Ovde kontrolišeš potrošnju i produženje.'}</p><div className="access-meta"><span><ShieldCheck size={14}/> {current.status}</span><span><CalendarDays size={14}/> {current.expires_at?`do ${fmtDate(current.expires_at)}`:'bez isteka'}</span>{daysLeft!==null&&<span className={daysLeft<=7?'expiry-hot':''}><Clock3 size={14}/> {daysLeft} dana preostalo</span>}</div></div><div className="usage-card"><span>Mesečna potrošnja</span><strong>{entitlement?.generated_this_month||0}<small> / {entitlement?.generation_limit??'∞'}</small></strong><div className="usage-track"><i style={{width:`${usagePercent}%`}}/></div><small>{entitlement?.restaurants_used||0}/{entitlement?.restaurants_limit??'∞'} lokacija</small></div></section>:<section className="billing-hero"><div><span className="billing-kicker"><Zap size={14}/> DESIGN · DISCOVERY · PUBLISH</span><h1>Izaberi paket i pokreni Autopilot.</h1><p>Pravi poslovni nalog: vizuali, sadržaj, discovery i raspored objava.</p></div><div className="license-activate"><div><KeyRound size={19}/><strong>Imaš licencu?</strong></div><div className="license-row"><input value={license} onChange={e=>setLicense(e.target.value.toUpperCase())} placeholder="RA-XXXX-XXXX-XXXX-XXXX"/><button onClick={redeem} disabled={working}>Aktiviraj</button></div></div></section>}
    {current&&<section className="renew-strip"><div><KeyRound size={18}/><div><strong>Aktivacioni kod za produženje</strong><span>Nova licenca može produžiti ili promeniti tvoj paket.</span></div></div><div className="renew-code"><input value={license} onChange={e=>setLicense(e.target.value.toUpperCase())} placeholder="RA-XXXX-XXXX-XXXX-XXXX"/><button onClick={redeem} disabled={working}>Aktiviraj</button></div></section>}
    {message&&<div className="billing-message">{message}</div>}
    <section className="billing-section-head"><div><p className="eyebrow">PAKETI</p><h2>{current?'Produži ili promeni paket':'Izaberi plan'}</h2></div><div className="billing-toggle"><button className={interval==='monthly'?'active':''} onClick={()=>setInterval('monthly')}>Mesečno</button><button className={interval==='yearly'?'active':''} onClick={()=>setInterval('yearly')}>Godišnje <span>2 meseca gratis</span></button></div></section>
    <section className="pricing-grid">{visiblePlans.map((plan,index)=><article className={`pricing-card ${index===1?'featured':''}`} key={plan.id}>{index===1&&<div className="popular-badge">NAJPOPULARNIJI</div>}<p className="eyebrow">{plan.name.toUpperCase()}</p><h2>{plan.price}<small> {plan.currency}</small></h2><span className="billing-period">/{plan.billing_interval==='yearly'?'god':'mes'}</span><p>{plan.description}</p><div className="plan-features"><span><CheckCircle2 size={14}/> {plan.max_restaurants} {plan.max_restaurants===1?'restoran':'restorana'}</span><span><CheckCircle2 size={14}/> {plan.monthly_generation_limit} generisanih objava mesečno</span><span><CheckCircle2 size={14}/> Brand Kit + Visual Studio</span><span><CheckCircle2 size={14}/> Publish Center + Smart Discovery</span>{Boolean(plan.features?.campaigns)&&<span><CheckCircle2 size={14}/> Campaign Autopilot</span>}</div><button className={index===1?'primary full':'secondary full'} onClick={()=>{setSelectedPlan(plan);setCreatedOrder(null);setMethod(methods.find(m=>m.enabled)?.key||'bank_transfer')}}>{current?`Produži · ${plan.name}`:`Izaberi ${plan.name}`}</button></article>)}</section>
    {!current&&settings?.trial_enabled&&<section className="trial-strip"><div><Clock3 size={20}/><div><strong>Želiš prvo da probaš?</strong><span>Jednokratni probni period otključava pravi nalog bez kartice.</span></div></div><button className="secondary" onClick={startTrial} disabled={working}>Aktiviraj probni period</button></section>}
    <section className="billing-management-grid"><div className="customer-orders"><div className="section-title"><div><p className="eyebrow">PRODAJNI NALOG</p><h2>Podaci za račun / fakturu</h2></div><button className="secondary" onClick={()=>setShowProfile(v=>!v)}><Pencil size={14}/> {showProfile?'Zatvori':'Izmeni'}</button></div>{showProfile?<ProfileEditor form={profileForm} setForm={setProfileForm} onSave={saveProfile} working={working}/>:<div className="profile-summary"><span><UserRound size={15}/><b>{profile?.full_name||'Ime nije uneseno'}</b></span><span><Building2 size={15}/>{profile?.billing_company||profile?.company||'Privatno lice / firma nije unesena'}</span><span><Mail size={15}/>{email}</span><span><MapPin size={15}/>{[profile?.billing_address,profile?.billing_city,profile?.billing_country].filter(Boolean).join(', ')||'Adresa nije unesena'}</span></div>}</div><div className="customer-orders notification-panel"><div className="section-title"><div><p className="eyebrow">OBAVEŠTENJA</p><h2>Status naloga</h2></div><Bell size={18}/></div>{notifications.length?notifications.slice(0,5).map(row=><button className={`notification-row ${row.read_at?'':'unread'}`} key={row.id} onClick={()=>void markNotificationRead(row)}><span><b>{row.subject}</b><small>{row.body}</small></span><time>{fmtDate(row.created_at)}</time></button>):<div className="admin-empty">Nema novih obaveštenja.</div>}</div></section>
    {orders.length>0&&<section className="customer-orders order-history"><div className="section-title"><div><p className="eyebrow">MOJE NARUDŽBINE</p><h2>Uplate i licence</h2></div><span className="order-pending-chip">{pendingOrders.length} čeka</span></div>{orders.map(order=><div className="customer-order-row customer-order-row-v2" key={order.id}><div><strong>{order.order_number}</strong><span>{order.sales_plans?.name||'Paket'} · {fmtDate(order.created_at)} · {paymentLabel(order.payment_method)}</span></div><b>{order.amount} {order.currency}</b><div className="order-reference"><span>Poziv / ref.</span><strong>{order.payment_reference||order.order_number}</strong></div><span className={`status ${order.status}`}>{order.status}</span><button className="icon-button" title="Kopiraj referencu" onClick={()=>copy(order.payment_reference||order.order_number)}><Copy size={14}/></button></div>)}</section>}
    {selectedPlan&&<div className="modal-backdrop" onMouseDown={()=>{if(!createdOrder)setSelectedPlan(null)}}><div className="modal-card sales-checkout sales-checkout-v2" onMouseDown={e=>e.stopPropagation()}>{createdOrder?<OrderCreated order={createdOrder} settings={settings} bankText={bankText} copy={copy} close={()=>{setSelectedPlan(null);setCreatedOrder(null)}}/>:<><p className="eyebrow">KUPOVINA / PRODUŽENJE</p><h2>{selectedPlan.name} · {selectedPlan.price} {selectedPlan.currency}</h2><p className="muted">Narudžbina ulazi direktno u Superadmin. Pristup se aktivira čim uplata bude potvrđena.</p><div className="payment-methods">{methods.filter(m=>m.enabled).map(entry=>{const Icon=entry.icon;return <button type="button" key={entry.key} className={method===entry.key?'active':''} onClick={()=>setMethod(entry.key)}><Icon size={18}/><span>{entry.label}</span></button>})}</div>{method==='bank_transfer'&&<div className="payment-help"><strong>Uplata na račun</strong><p>{bankText||'Podatke za račun Superadmin treba da unese u Prodajna podešavanja. Narudžbina će ipak dobiti jedinstven poziv na broj.'}</p></div>}{method==='invoice'&&<div className="payment-help"><strong>Predračun / faktura</strong><p>Podaci iz tvog prodajnog profila biće sačuvani uz narudžbinu.</p></div>}{method==='paypal'&&<div className="payment-help"><strong>PayPal</strong><p>Posle kreiranja narudžbine otvara se podešeni PayPal payment link.</p></div>}<button type="button" className="billing-inline-profile" onClick={()=>setShowProfile(true)}><UserRound size={15}/><span>{profileForm.full_name||'Dodaj podatke kupca'} · {profileForm.company||'privatno lice'}</span><Pencil size={13}/></button><label>Napomena<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="PIB, kontakt, posebna napomena..."/></label><div className="modal-actions"><button className="secondary" onClick={()=>setSelectedPlan(null)}>Otkaži</button><button className="primary" onClick={createOrder} disabled={working}><ShieldCheck size={16}/>{working?'Kreiram…':'Potvrdi narudžbinu'}</button></div></>}</div></div>}
  </div>
}

function ProfileEditor({form,setForm,onSave,working}:{form:ProfileForm;setForm:(v:ProfileForm)=>void;onSave:(e?:FormEvent)=>Promise<void>;working:boolean}){return <form className="billing-profile-form" onSubmit={onSave}><div className="billing-profile-grid"><label>Ime i prezime<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Telefon<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Firma<input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label>PIB<input value={form.tax_id} onChange={e=>setForm({...form,tax_id:e.target.value})}/></label><label>Matični broj<input value={form.company_number} onChange={e=>setForm({...form,company_number:e.target.value})}/></label><label>Adresa<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Grad<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Država<input value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label></div><button className="primary" disabled={working}><Save size={15}/> Sačuvaj podatke</button></form>}
function OrderCreated({order,settings,bankText,copy,close}:{order:SalesOrder;settings:SalesSettings|null;bankText:string;copy:(v:string)=>void;close:()=>void}){const reference=order.payment_reference||order.order_number;return <div className="order-created"><div className="order-created-icon"><CheckCircle2 size={28}/></div><p className="eyebrow">NARUDŽBINA KREIRANA</p><h2>{order.order_number}</h2><p>Sačuvaj referencu ispod. Superadmin vidi zahtev odmah.</p><div className="payment-ticket"><div><span>Iznos</span><strong>{order.amount} {order.currency}</strong></div><div><span>Poziv / referenca</span><strong>{reference}</strong><button onClick={()=>copy(reference)}><Copy size={13}/> kopiraj</button></div>{order.due_at&&<div><span>Rok</span><strong>{fmtDate(order.due_at)}</strong></div>}</div>{order.payment_method==='bank_transfer'&&<div className="payment-help payment-help-final"><strong>Podaci za uplatu</strong><p>{bankText||'Kontaktiraj prodaju za podatke za uplatu.'}</p></div>}{order.payment_method==='invoice'&&<div className="payment-help payment-help-final"><strong>Predračun / faktura</strong><p>{settings?.invoice_note||'Zahtev za predračun je evidentiran. Administrator ga obrađuje iz Superadmin panela.'}</p></div>}<button className="primary full" onClick={close}>Završi</button></div>}
function fmtDate(v:string){return new Date(v).toLocaleDateString('sr-RS',{day:'2-digit',month:'2-digit',year:'numeric'})}
function paymentLabel(v:SalesOrder['payment_method']){return({bank_transfer:'uplata na račun',invoice:'faktura',paypal:'PayPal',card:'kartica',cash:'keš',manual:'ručno',license_code:'licenca'} as Record<string,string>)[v]||v}
function humanError(v:string){if(v.includes('already been used'))return'Ovaj aktivacioni kod je već iskorišćen.';if(v.includes('assigned to another email'))return'Licenca je vezana za drugi email.';if(v.includes('Trial has already been used'))return'Probni period je već iskorišćen na ovom nalogu.';if(v.includes('skoro kreiran'))return'Već postoji skoro kreirana narudžbina za isti paket i način plaćanja.';return v}
