import { useState } from 'react'
import { Activity, BadgeEuro, Bell, CheckCircle2, CircleDollarSign, Download, Eye, EyeOff, Image as ImageIcon, KeyRound, Megaphone, Power, Save, Search, Settings2, ShieldCheck, Sparkles, Store, TicketCheck, UsersRound, WalletCards, WandSparkles } from 'lucide-react'

type View='overview'|'customers'|'sales'|'licenses'|'plans'|'system'
type ToggleState={maintenance:boolean;sales:boolean;signup:boolean;ai:boolean;announcement:boolean}

const customers=[
  {name:'Bella Napoli',email:'info@bellanapoli.rs',locations:1,plan:'PRO',status:'active',posts:34,ai:7,until:'10.10.2026'},
  {name:'Urban Burger',email:'office@urbanburger.rs',locations:2,plan:'BUSINESS',status:'active',posts:81,ai:19,until:'02.11.2026'},
  {name:'Stara Česma',email:'restoran@staracesma.rs',locations:1,plan:'START',status:'trialing',posts:8,ai:2,until:'17.09.2026'},
]
const orders=[
  {id:'RA-260910-8F12A1',email:'office@urbanburger.rs',plan:'Business',amount:'79 EUR',status:'paid'},
  {id:'RA-260910-11AE92',email:'info@bellanapoli.rs',plan:'Pro',amount:'49 EUR',status:'paid'},
  {id:'RA-260910-781BD0',email:'restoran@staracesma.rs',plan:'Start godišnje',amount:'290 EUR',status:'pending'},
]
const initialPlans=[
  {name:'Start',code:'START-M',price:29,posts:20,restaurants:1,ai:5,weekly:5,campaign:false},
  {name:'Pro',code:'PRO-M',price:49,posts:50,restaurants:2,ai:25,weekly:7,campaign:true},
  {name:'Business',code:'BUSINESS-M',price:79,posts:120,restaurants:5,ai:75,weekly:7,campaign:true},
]

export function DemoOwner({notify}:{notify:(v:string)=>void}){
  const[view,setView]=useState<View>('overview')
  const[toggles,setToggles]=useState<ToggleState>({maintenance:false,sales:true,signup:true,ai:true,announcement:true})
  const[plans,setPlans]=useState(initialPlans)
  const[search,setSearch]=useState('')
  const filtered=customers.filter(x=>`${x.name} ${x.email} ${x.plan}`.toLowerCase().includes(search.toLowerCase()))
  const flip=(key:keyof ToggleState)=>setToggles(s=>({...s,[key]:!s[key]}))
  return <div className="superadmin-page superadmin-v2 owner-control-v3 demo-owner-page">
    <header className="admin-topbar"><div><span className="admin-shield"><ShieldCheck size={21}/></span><div><p>RESTAURANT AUTOPILOT</p><h1>OWNER Control Center</h1></div></div><div className="admin-top-actions"><span className={`admin-live ${toggles.maintenance?'owner-offline':''}`}><i/>{toggles.maintenance?'MAINTENANCE':'SYSTEM ONLINE'}</span><button className="secondary" onClick={()=>notify('Demo OWNER backup je pripremljen.')}><Download size={15}/> Backup</button></div></header>
    <nav className="admin-tabs owner-tabs"><T active={view==='overview'} onClick={()=>setView('overview')} icon={<Activity size={16}/>} label="Pregled"/><T active={view==='customers'} onClick={()=>setView('customers')} icon={<UsersRound size={16}/>} label="Kupci"/><T active={view==='sales'} onClick={()=>setView('sales')} icon={<WalletCards size={16}/>} label="Prodaja" count={1}/><T active={view==='licenses'} onClick={()=>setView('licenses')} icon={<KeyRound size={16}/>} label="Licence"/><T active={view==='plans'} onClick={()=>setView('plans')} icon={<BadgeEuro size={16}/>} label="Paketi"/><T active={view==='system'} onClick={()=>setView('system')} icon={<Settings2 size={16}/>} label="Sistem"/></nav>

    {view==='overview'&&<><section className="admin-metrics owner-metrics"><M icon={<UsersRound size={18}/>} label="Registrovani" value="127"/><M icon={<Store size={18}/>} label="Restorani" value="148"/><M icon={<TicketCheck size={18}/>} label="Aktivni paketi" value="91"/><M icon={<CircleDollarSign size={18}/>} label="Ovaj mesec" value="4.362 €"/><M icon={<Sparkles size={18}/>} label="Objave / mes" value="3.814"/><M icon={<ImageIcon size={18}/>} label="AI slike / mes" value="806"/></section><section className="owner-health-grid"><H icon={<Power size={18}/>} title="Aplikacija" value={toggles.maintenance?'Maintenance':'Online'} ok={!toggles.maintenance} detail="v1.0"/><H icon={<WalletCards size={18}/>} title="Prodaja" value={toggles.sales?'Otvorena':'Zatvorena'} ok={toggles.sales} detail="1 čeka uplatu"/><H icon={<WandSparkles size={18}/>} title="AI Food Image" value={toggles.ai?'Spreman':'Pauziran'} ok={toggles.ai} detail="806 ovog meseca"/><H icon={<Bell size={18}/>} title="Outbox" value="3 čekaju" ok={false} detail="email + in-app"/></section><div className="admin-overview-grid"><section className="admin-panel demo-owner-action"><p className="eyebrow">BRZA PRODAJA</p><h2>Aktiviraj kupca odmah</h2><label>Kupac<select><option>info@bellanapoli.rs</option><option>office@urbanburger.rs</option></select></label><label>Paket<select><option>Pro · 49 EUR</option><option>Business · 79 EUR</option></select></label><div className="demo-owner-two"><label>Dana<input value="365" readOnly/></label><label>Naplaćeno<input value="490" readOnly/></label></div><button className="primary full" onClick={()=>notify('Demo: kupac je aktiviran i prodaja evidentirana.')}><CheckCircle2 size={15}/> Aktiviraj i evidentiraj</button></section><section className="admin-panel demo-owner-action"><p className="eyebrow">AKTIVACIONI KOD</p><h2>Prodaj licencu</h2><label>Paket<select><option>Pro godišnje</option><option>Business godišnje</option></select></label><label>Email<input value="novi@restoran.rs" readOnly/></label><div className="generated-license demo-generated"><span>KOD SE PRIKAZUJE SAMO JEDNOM</span><strong>RA-84KD-92LP-X7Q2</strong><small>PRO · 365 dana</small></div><button className="secondary full" onClick={()=>notify('Demo licenca je kopirana.')}><KeyRound size={15}/> Generiši novu licencu</button></section></div><section className="admin-panel"><p className="eyebrow">POSLEDNJE NARUDŽBINE</p><h2>Prodajni tok</h2><OrderTable rows={orders} notify={notify}/></section></>}

    {view==='customers'&&<section className="admin-panel"><div className="admin-panel-head admin-customers-head"><div><p className="eyebrow">KUPCI I KORIŠĆENJE</p><h2>Svi nalozi pod tvojom kontrolom</h2></div><div className="admin-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Email, restoran, paket..."/></div></div><div className="demo-owner-customer-grid">{filtered.map(c=><article key={c.email}><div className="demo-owner-customer-head"><div><strong>{c.name}</strong><small>{c.email}</small></div><span className={`status ${c.status}`}>{c.status}</span></div><div className="demo-owner-customer-stats"><span><b>{c.plan}</b><small>paket</small></span><span><b>{c.locations}</b><small>lokacije</small></span><span><b>{c.posts}</b><small>objave</small></span><span><b>{c.ai}</b><small>AI slike</small></span></div><div className="demo-owner-until">Važi do <strong>{c.until}</strong></div><div className="admin-row-actions"><button onClick={()=>notify(`${c.name}: +30 dana`)}>+30d</button><button onClick={()=>notify(`${c.name}: +1 godina`)}>+1g</button><button onClick={()=>notify(`Poruka za ${c.email}`)}>Poruka</button><button className="danger-soft" onClick={()=>notify(`${c.name}: demo suspenzija`)}>Suspenduj</button></div></article>)}</div></section>}

    {view==='sales'&&<section className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">PRODAJA</p><h2>Narudžbine, uplate i refundi</h2></div><button className="secondary" onClick={()=>notify('CSV prodaje je spreman.')}><Download size={14}/> CSV</button></div><OrderTable rows={orders} notify={notify}/></section>}

    {view==='licenses'&&<div className="admin-two-column"><section className="admin-panel demo-owner-action"><p className="eyebrow">NOVA LICENCA</p><h2>Prodaj aktivacioni kod</h2><label>Paket<select><option>Start godišnje</option><option>Pro godišnje</option><option>Business godišnje</option></select></label><label>Email<input placeholder="kupac@restoran.rs"/></label><label>Trajanje<input value="365 dana" readOnly/></label><button className="primary full" onClick={()=>notify('Demo: generisan RA kod.')}><KeyRound size={15}/> Generiši licencu</button></section><section className="admin-panel"><p className="eyebrow">IZDATE LICENCE</p><h2>Kodovi i status</h2>{['•••• X7Q2 · PRO','•••• 91AB · BUSINESS','•••• 2F8K · START'].map((x,i)=><div className="license-row-admin" key={x}><div><strong>{x}</strong><span>{i===1?'office@urbanburger.rs':'kupac@restoran.rs'}</span></div><span className={`status ${i===2?'depleted':'active'}`}>{i===2?'iskorišćena':'active'}</span><button className="danger-soft" onClick={()=>notify('Demo: licenca opozvana.')}>Opozovi</button></div>)}</section></div>}

    {view==='plans'&&<section className="admin-panel"><p className="eyebrow">PAKETI, CENE I FUNKCIJE</p><h2>Ti određuješ šta svaki kupac dobija</h2><div className="owner-plan-grid">{plans.map((p,index)=><article className="owner-plan-card" key={p.code}><div className="owner-plan-head"><div><span>monthly</span><b>{p.code}</b></div><div><button className="on">AKTIVAN</button><button className="on">JAVAN</button></div></div><h3>{p.name}</h3><div className="owner-plan-fields"><label>Cena<input type="number" value={p.price} onChange={e=>setPlans(list=>list.map((x,i)=>i===index?{...x,price:Number(e.target.value)}:x))}/></label><label>Objava/mes<input type="number" value={p.posts} onChange={e=>setPlans(list=>list.map((x,i)=>i===index?{...x,posts:Number(e.target.value)}:x))}/></label><label>Restorana<input type="number" value={p.restaurants} onChange={e=>setPlans(list=>list.map((x,i)=>i===index?{...x,restaurants:Number(e.target.value)}:x))}/></label><label>AI slika/mes<input type="number" value={p.ai} onChange={e=>setPlans(list=>list.map((x,i)=>i===index?{...x,ai:Number(e.target.value)}:x))}/></label><label>Objava/nedelja<input type="number" value={p.weekly} onChange={e=>setPlans(list=>list.map((x,i)=>i===index?{...x,weekly:Number(e.target.value)}:x))}/></label></div><label className={`sales-toggle ${p.campaign?'on':''}`}><input type="checkbox" checked={p.campaign} onChange={e=>setPlans(list=>list.map((x,i)=>i===index?{...x,campaign:e.target.checked}:x))}/><span/><b>Campaign Pack</b></label><button className="primary full" onClick={()=>notify(`${p.name}: demo paket sačuvan.`)}><Save size={14}/> Sačuvaj paket</button></article>)}</div></section>}

    {view==='system'&&<div className="owner-system-grid"><section className="admin-panel"><p className="eyebrow">GLOBALNA KONTROLA</p><h2>Aplikacija i prodaja</h2><div className="owner-switch-stack"><Switch icon={<Power size={18}/>} title="Maintenance mode" detail="Blokira kupce dok radiš kritične izmene." value={toggles.maintenance} click={()=>flip('maintenance')} danger/><Switch icon={<WalletCards size={18}/>} title="Prodaja otvorena" detail="Gasi ili pušta nove narudžbine server-side." value={toggles.sales} click={()=>flip('sales')}/><Switch icon={<UsersRound size={18}/>} title="Registracije otvorene" detail="Kontrola novih naloga." value={toggles.signup} click={()=>flip('signup')}/><Switch icon={<ImageIcon size={18}/>} title="AI fotografije" detail="Globalni AI food generator." value={toggles.ai} click={()=>flip('ai')}/><Switch icon={<Megaphone size={18}/>} title="Globalno obaveštenje" detail="Poruka svim korisnicima aplikacije." value={toggles.announcement} click={()=>flip('announcement')}/></div><label className="demo-owner-wide">Poruka korisnicima<textarea defaultValue="Nova verzija Creative AI je dostupna svim aktivnim korisnicima."/></label><button className="primary" onClick={()=>notify('Demo globalna podešavanja su sačuvana.')}><Save size={15}/> Sačuvaj sistem</button></section><section className="admin-panel"><p className="eyebrow">AI PROVIDER</p><h2>Food Image Engine</h2><div className={`owner-ai-status ${toggles.ai?'ready':''}`}><span><WandSparkles size={23}/></span><div><strong>{toggles.ai?'OpenAI ključ je podešen':'AI je pauziran'}</strong><small>Ključ se čuva server-side i kupci ga nikada ne vide.</small></div></div><label className="owner-ai-key">OpenAI API ključ<input type="password" placeholder="Novi sk-… samo ako menjaš"/></label><button className="secondary full" onClick={()=>notify('Demo: AI provider sačuvan.')}><KeyRound size={15}/> Promeni AI ključ</button><div className="owner-ai-usage"><div><span>Ovog meseca</span><strong>806</strong><small>AI food slika</small></div><div><span>Ukupno</span><strong>2.914</strong><small>sačuvanih asseta</small></div></div></section></div>}
  </div>
}

function T({active,onClick,icon,label,count}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string;count?:number}){return <button className={active?'active':''} onClick={onClick}>{icon}{label}{count?<b>{count}</b>:null}</button>}
function M({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="admin-metric"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function H({icon,title,value,detail,ok}:{icon:React.ReactNode;title:string;value:string;detail:string;ok:boolean}){return <div className={`owner-health ${ok?'ok':''}`}><span>{icon}</span><div><small>{title}</small><strong>{value}</strong><p>{detail}</p></div><i/></div>}
function Switch({icon,title,detail,value,click,danger=false}:{icon:React.ReactNode;title:string;detail:string;value:boolean;click:()=>void;danger?:boolean}){return <button className={`owner-big-toggle ${value?'on':''} ${danger?'danger-mode':''}`} onClick={click}><span>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><b>{value?<Eye size={15}/>:<EyeOff size={15}/>} {value?'UKLJUČENO':'ISKLJUČENO'}</b></button>}
function OrderTable({rows,notify}:{rows:typeof orders;notify:(v:string)=>void}){return <div className="admin-table orders-table orders-table-v2"><div className="admin-table-head"><span>Narudžbina</span><span>Kupac</span><span>Paket</span><span>Iznos</span><span>Status</span><span>Akcija</span></div>{rows.map(o=><div className="admin-table-row" key={o.id}><div><strong>{o.id}</strong><small>danas · ref {o.id}</small></div><div><strong>{o.email}</strong></div><div><strong>{o.plan}</strong></div><strong>{o.amount}</strong><span className={`status ${o.status}`}>{o.status}</span><div className="order-admin-actions">{o.status==='pending'?<button className="paid-button" onClick={()=>notify(`${o.id}: demo uplata potvrđena.`)}>Uplata primljena</button>:<button className="refund-button" onClick={()=>notify(`${o.id}: demo refund.`)}>Refund</button>}</div></div>)}</div>}
