import { type ReactNode, useEffect, useMemo, useState } from 'react'
import { Activity, BadgeEuro, Ban, Bell, BookOpenCheck, CheckCircle2, CircleDollarSign, Copy, Download, Eye, EyeOff, Image as ImageIcon, KeyRound, Mail, Megaphone, Power, RefreshCw, Save, Search, Settings2, ShieldCheck, Sparkles, Store, TicketCheck, UsersRound, WalletCards, WandSparkles } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { AdminAuditLog, CustomerProfile, CustomerSubscription, LicenseCodeRow, NotificationOutbox, SalesOrder, SalesPlan, SalesSettings } from '../types'

type View = 'overview'|'customers'|'sales'|'licenses'|'plans'|'system'|'messages'|'audit'
type RestaurantLite = { id:string; owner_id:string; name:string; city:string|null; created_at:string }
type PostLite = { id:string; restaurant_id:string; status:string; created_at:string }
type CreativeLite = { id:string; user_id:string; restaurant_id:string; created_at:string }
type AppControls = {
  id:number; app_name:string; app_version:string; maintenance_mode:boolean; maintenance_message:string|null
  sales_open:boolean; signup_open:boolean; ai_images_enabled:boolean; announcement_enabled:boolean
  announcement_text:string|null; announcement_tone:'info'|'success'|'warning'; support_whatsapp:string|null; updated_at:string
}
type SaleForm={userId:string;planId:string;days:string;amount:string;paymentMethod:string;note:string}
type LicenseForm={planId:string;email:string;days:string;amount:string;paymentMethod:string;note:string}
type Generated={id:string;code:string;plan:string;assigned_email:string|null}

const methods=[['manual','Ručno / ostalo'],['bank_transfer','Uplata na račun'],['invoice','Predračun / faktura'],['paypal','PayPal'],['card','Kartica'],['cash','Keš']] as const
const freshSale:SaleForm={userId:'',planId:'',days:'',amount:'',paymentMethod:'manual',note:''}
const freshLicense:LicenseForm={planId:'',email:'',days:'',amount:'',paymentMethod:'manual',note:''}
const defaultControls:AppControls={id:1,app_name:'Restaurant Autopilot',app_version:'1.0',maintenance_mode:false,maintenance_message:null,sales_open:true,signup_open:true,ai_images_enabled:true,announcement_enabled:false,announcement_text:null,announcement_tone:'info',support_whatsapp:null,updated_at:''}

export function OwnerControl({onCloseApp,setNotice}:{onCloseApp?:()=>void;setNotice:(v:string)=>void}){
  const [view,setView]=useState<View>('overview')
  const [profiles,setProfiles]=useState<CustomerProfile[]>([]),[restaurants,setRestaurants]=useState<RestaurantLite[]>([]),[plans,setPlans]=useState<SalesPlan[]>([])
  const [subs,setSubs]=useState<CustomerSubscription[]>([]),[orders,setOrders]=useState<SalesOrder[]>([]),[licenses,setLicenses]=useState<LicenseCodeRow[]>([])
  const [settings,setSettings]=useState<SalesSettings|null>(null),[controls,setControls]=useState<AppControls>(defaultControls),[outbox,setOutbox]=useState<NotificationOutbox[]>([]),[audit,setAudit]=useState<AdminAuditLog[]>([])
  const [posts,setPosts]=useState<PostLite[]>([]),[creative,setCreative]=useState<CreativeLite[]>([]),[aiConfigured,setAiConfigured]=useState(false)
  const [working,setWorking]=useState(false),[search,setSearch]=useState(''),[sale,setSale]=useState<SaleForm>(freshSale),[license,setLicense]=useState<LicenseForm>(freshLicense),[generated,setGenerated]=useState<Generated|null>(null)
  const [noteTarget,setNoteTarget]=useState<CustomerProfile|null>(null),[noteSubject,setNoteSubject]=useState('Restaurant Autopilot'),[noteBody,setNoteBody]=useState(''),[aiKey,setAiKey]=useState('')

  useEffect(()=>{void load(true)},[])

  async function load(housekeeping=false){
    setWorking(true)
    if(housekeeping) await supabase.rpc('admin_housekeeping')
    const [a,b,c,d,e,f,g,h,i,j,k,l,m]=await Promise.all([
      supabase.from('customer_profiles').select('*').order('created_at',{ascending:false}),
      supabase.from('restaurants').select('id,owner_id,name,city,created_at').order('created_at',{ascending:false}),
      supabase.from('sales_plans').select('*').order('sort_order'),
      supabase.from('customer_subscriptions').select('*, sales_plans(*)').order('created_at',{ascending:false}),
      supabase.from('sales_orders').select('*, sales_plans(*)').order('created_at',{ascending:false}),
      supabase.from('license_codes').select('*, sales_plans(*)').order('created_at',{ascending:false}).limit(250),
      supabase.from('sales_settings').select('*').eq('id',1).maybeSingle(),
      supabase.from('notification_outbox').select('*').order('created_at',{ascending:false}).limit(250),
      supabase.from('admin_audit_log').select('*').order('created_at',{ascending:false}).limit(300),
      supabase.from('app_controls').select('*').eq('id',1).maybeSingle(),
      supabase.from('posts').select('id,restaurant_id,status,created_at').order('created_at',{ascending:false}).limit(5000),
      supabase.from('creative_assets').select('id,user_id,restaurant_id,created_at').order('created_at',{ascending:false}).limit(5000),
      supabase.rpc('admin_ai_provider_status'),
    ])
    const err=a.error||b.error||c.error||d.error||e.error||f.error||g.error||h.error||i.error||j.error||k.error||l.error||m.error
    if(err)setNotice(err.message)
    setProfiles((a.data||[]) as CustomerProfile[]);setRestaurants((b.data||[]) as RestaurantLite[]);setPlans((c.data||[]) as SalesPlan[]);setSubs((d.data||[]) as CustomerSubscription[]);setOrders((e.data||[]) as SalesOrder[]);setLicenses((f.data||[]) as LicenseCodeRow[]);setSettings((g.data||null) as SalesSettings|null);setOutbox((h.data||[]) as NotificationOutbox[]);setAudit((i.data||[]) as AdminAuditLog[]);setControls((j.data||defaultControls) as AppControls);setPosts((k.data||[]) as PostLite[]);setCreative((l.data||[]) as CreativeLite[]);setAiConfigured(Boolean((m.data as any)?.configured));setWorking(false)
  }

  const active=useMemo(()=>subs.filter(s=>['active','trialing'].includes(s.status)&&(!s.expires_at||new Date(s.expires_at).getTime()>Date.now())),[subs])
  const pending=useMemo(()=>orders.filter(o=>o.status==='pending'),[orders])
  const revenue=useMemo(()=>orders.filter(o=>o.status==='paid').reduce((n,o)=>n+Number(o.amount||0),0),[orders])
  const monthRevenue=useMemo(()=>orders.filter(o=>o.status==='paid'&&sameMonth(o.paid_at||o.created_at,new Date())).reduce((n,o)=>n+Number(o.amount||0),0),[orders])
  const monthPosts=useMemo(()=>posts.filter(p=>sameMonth(p.created_at,new Date())).length,[posts])
  const monthAi=useMemo(()=>creative.filter(p=>sameMonth(p.created_at,new Date())).length,[creative])
  const expiring=useMemo(()=>active.filter(s=>s.expires_at&&daysTo(s.expires_at)<=7&&daysTo(s.expires_at)>=0),[active])
  const queued=useMemo(()=>outbox.filter(x=>x.delivery_status==='queued'),[outbox])
  const profileByUser=useMemo(()=>new Map(profiles.map(p=>[p.user_id,p])),[profiles])
  const subByUser=useMemo(()=>{const map=new Map<string,CustomerSubscription>();subs.forEach(s=>{if(!map.has(s.user_id))map.set(s.user_id,s)});return map},[subs])
  const restaurantsByUser=useMemo(()=>{const map=new Map<string,RestaurantLite[]>();restaurants.forEach(r=>map.set(r.owner_id,[...(map.get(r.owner_id)||[]),r]));return map},[restaurants])
  const ownerByRestaurant=useMemo(()=>new Map(restaurants.map(r=>[r.id,r.owner_id])),[restaurants])
  const postCountByUser=useMemo(()=>{const map=new Map<string,number>();posts.forEach(p=>{const u=ownerByRestaurant.get(p.restaurant_id);if(u)map.set(u,(map.get(u)||0)+1)});return map},[posts,ownerByRestaurant])
  const aiCountByUser=useMemo(()=>{const map=new Map<string,number>();creative.forEach(x=>map.set(x.user_id,(map.get(x.user_id)||0)+1));return map},[creative])
  const customers=useMemo(()=>{const q=search.toLowerCase().trim();return q?profiles.filter(p=>`${p.email} ${p.full_name||''} ${p.company||''} ${(restaurantsByUser.get(p.user_id)||[]).map(r=>r.name).join(' ')}`.toLowerCase().includes(q)):profiles},[profiles,search,restaurantsByUser])

  async function paid(o:SalesOrder){setWorking(true);const{error}=await supabase.rpc('admin_mark_order_paid',{p_order_id:o.id,p_admin_note:'Potvrđeno iz OWNER panela'});if(error)setNotice(error.message);else{setNotice(`${o.order_number}: uplata potvrđena i pristup aktiviran.`);await load()}setWorking(false)}
  async function cancel(o:SalesOrder){if(!confirm(`Otkaži ${o.order_number}?`))return;const{error}=await supabase.from('sales_orders').update({status:'cancelled',admin_note:'Otkazano iz OWNER panela'}).eq('id',o.id);if(error)setNotice(error.message);else{setNotice('Narudžbina je otkazana.');await load()}}
  async function refund(o:SalesOrder){if(!confirm(`Refund ${o.order_number} i suspenduj pristup?`))return;setWorking(true);const{error}=await supabase.rpc('admin_refund_order',{p_order_id:o.id,p_suspend_access:true,p_note:'Refund iz OWNER panela'});if(error)setNotice(error.message);else{setNotice('Refund je evidentiran i pristup zatvoren.');await load()}setWorking(false)}
  async function grant(){if(!sale.userId||!sale.planId){setNotice('Izaberi kupca i paket.');return}setWorking(true);const{error}=await supabase.rpc('admin_grant_access',{p_user_id:sale.userId,p_plan_id:sale.planId,p_days:sale.days?Number(sale.days):null,p_payment_method:sale.paymentMethod,p_amount:sale.amount?Number(sale.amount):null,p_note:sale.note||null});if(error)setNotice(error.message);else{setNotice('Kupac je aktiviran i prodaja evidentirana.');setSale(freshSale);await load()}setWorking(false)}
  async function makeLicense(){if(!license.planId){setNotice('Izaberi paket.');return}setWorking(true);const{data,error}=await supabase.rpc('admin_create_license_code',{p_plan_id:license.planId,p_duration_days:license.days?Number(license.days):null,p_assigned_email:license.email||null,p_sale_amount:license.amount?Number(license.amount):null,p_payment_method:license.paymentMethod,p_note:license.note||null});if(error)setNotice(error.message);else{setGenerated(data as Generated);setNotice('Licenca je napravljena. Puni kod kopiraj sada.');setLicense(freshLicense);await load()}setWorking(false)}
  async function extend(s:CustomerSubscription,days:number){const d=s.expires_at&&new Date(s.expires_at).getTime()>Date.now()?new Date(s.expires_at):new Date();d.setDate(d.getDate()+days);const{error}=await supabase.from('customer_subscriptions').update({expires_at:d.toISOString(),status:'active'}).eq('id',s.id);if(error)setNotice(error.message);else{setNotice(`Pristup produžen za ${days} dana.`);await load()}}
  async function setSubStatus(s:CustomerSubscription,status:CustomerSubscription['status']){const{error}=await supabase.from('customer_subscriptions').update({status}).eq('id',s.id);if(error)setNotice(error.message);else{setNotice(status==='suspended'?'Kupac je suspendovan.':'Kupac je ponovo aktivan.');await load()}}
  async function revoke(x:LicenseCodeRow){if(!confirm('Opozovi ovu licencu?'))return;const{error}=await supabase.from('license_codes').update({status:'revoked'}).eq('id',x.id);if(error)setNotice(error.message);else await load()}
  async function savePlan(p:SalesPlan,patch:{price:number;monthly_generation_limit:number;max_restaurants:number;trial_days:number;active:boolean;public:boolean;features:Record<string,unknown>}){const{error}=await supabase.from('sales_plans').update(patch).eq('id',p.id);if(error)setNotice(error.message);else{setNotice(`${p.name}: paket i funkcije su sačuvani.`);await load()}}
  async function saveSystem(){setWorking(true);const{error}=await supabase.from('app_controls').update({...controls,updated_at:new Date().toISOString()}).eq('id',1);if(error)setNotice(error.message);else{setNotice('Globalna kontrola aplikacije je sačuvana.');await load()}setWorking(false)}
  async function saveSales(){if(!settings)return;setWorking(true);const{error}=await supabase.from('sales_settings').update(settings).eq('id',1);if(error)setNotice(error.message);else setNotice('Firma, banka i načini prodaje su sačuvani.');setWorking(false)}
  async function saveAiKey(){if(!aiKey.trim()){setNotice('Unesi OpenAI API ključ.');return}setWorking(true);const{error}=await supabase.rpc('admin_set_ai_provider_key',{p_key:aiKey.trim()});if(error)setNotice(error.message);else{setAiKey('');setAiConfigured(true);setNotice('AI provider je aktiviran server-side. Ključ se ne prikazuje kupcima.')}setWorking(false)}
  async function sendNote(){if(!noteTarget||!noteSubject.trim()||!noteBody.trim()){setNotice('Upiši naslov i poruku.');return}setWorking(true);const{error}=await supabase.rpc('admin_send_note',{p_user_id:noteTarget.user_id,p_subject:noteSubject.trim(),p_body:noteBody.trim()});if(error)setNotice(error.message);else{setNotice('Poruka je dodata kupcu i u Outbox.');setNoteTarget(null);setNoteBody('');await load()}setWorking(false)}
  async function markOut(x:NotificationOutbox,status:'sent'|'dismissed'){const patch=status==='sent'?{delivery_status:'sent',sent_at:new Date().toISOString()}:{delivery_status:'dismissed'};const{error}=await supabase.from('notification_outbox').update(patch).eq('id',x.id);if(error)setNotice(error.message);else await load()}
  function copy(v:string){navigator.clipboard.writeText(v).then(()=>setNotice('Kopirano.')).catch(()=>setNotice('Browser nije dozvolio kopiranje.'))}
  function exportSales(){downloadCsv('restaurant-autopilot-prodaja.csv',[['narudzbina','datum','kupac','paket','status','nacin','iznos','valuta','referenca'],...orders.map(o=>[o.order_number,o.created_at,profileByUser.get(o.user_id)?.email||o.user_id,o.sales_plans?.name||'',o.status,o.payment_method,String(o.amount),o.currency,o.payment_reference||''])]);setNotice('Prodaja je izvezena u CSV.')}
  function exportCustomers(){downloadCsv('restaurant-autopilot-kupci.csv',[['email','ime','firma','restorani','paket','status','vazi_do','objave','ai_slike'],...profiles.map(p=>{const s=subByUser.get(p.user_id);return[p.email,p.full_name||'',p.company||'',String((restaurantsByUser.get(p.user_id)||[]).length),s?.sales_plans?.name||'',s?.status||'',s?.expires_at||'',String(postCountByUser.get(p.user_id)||0),String(aiCountByUser.get(p.user_id)||0)]})]);setNotice('Kupci su izvezeni u CSV.')}
  function backup(){const payload={exported_at:new Date().toISOString(),app_controls:controls,sales_settings:settings,plans,profiles,restaurants,subscriptions:subs,orders,licenses,creative_assets:creative,posts_summary:posts,outbox,audit};downloadText(`restaurant-autopilot-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2),'application/json');setNotice('OWNER backup snapshot je preuzet.')}

  return <div className="superadmin-page superadmin-v2 owner-control-v3">
    <header className="admin-topbar"><div><span className="admin-shield"><ShieldCheck size={21}/></span><div><p>RESTAURANT AUTOPILOT</p><h1>OWNER Control Center</h1></div></div><div className="admin-top-actions"><span className={`admin-live ${controls.maintenance_mode?'owner-offline':''}`}><i/> {controls.maintenance_mode?'MAINTENANCE':'SYSTEM ONLINE'}</span><button className="secondary" onClick={backup}><Download size={15}/> Backup</button><button className="secondary" onClick={()=>void load(true)} disabled={working}><RefreshCw size={15}/> Osveži</button>{onCloseApp&&<button className="secondary" onClick={onCloseApp}>Nazad u app</button>}</div></header>
    <nav className="admin-tabs owner-tabs"><Tab a={view==='overview'} f={()=>setView('overview')} i={<Activity size={16}/>} l="Pregled"/><Tab a={view==='customers'} f={()=>setView('customers')} i={<UsersRound size={16}/>} l="Kupci"/><Tab a={view==='sales'} f={()=>setView('sales')} i={<WalletCards size={16}/>} l="Prodaja" c={pending.length}/><Tab a={view==='licenses'} f={()=>setView('licenses')} i={<KeyRound size={16}/>} l="Licence"/><Tab a={view==='plans'} f={()=>setView('plans')} i={<BadgeEuro size={16}/>} l="Paketi"/><Tab a={view==='system'} f={()=>setView('system')} i={<Settings2 size={16}/>} l="Sistem"/><Tab a={view==='messages'} f={()=>setView('messages')} i={<Bell size={16}/>} l="Poruke" c={queued.length}/><Tab a={view==='audit'} f={()=>setView('audit')} i={<BookOpenCheck size={16}/>} l="Audit"/></nav>

    {view==='overview'&&<><section className="admin-metrics owner-metrics"><Metric i={<UsersRound size={18}/>} l="Registrovani" v={profiles.length}/><Metric i={<Store size={18}/>} l="Restorani" v={restaurants.length}/><Metric i={<TicketCheck size={18}/>} l="Aktivni paketi" v={active.length}/><Metric i={<CircleDollarSign size={18}/>} l="Ovaj mesec" v={`${monthRevenue.toFixed(0)} €`}/><Metric i={<Sparkles size={18}/>} l="Objave / mes" v={monthPosts}/><Metric i={<ImageIcon size={18}/>} l="AI slike / mes" v={monthAi}/></section>
      <section className="owner-health-grid"><HealthCard icon={<Power size={18}/>} title="Aplikacija" value={controls.maintenance_mode?'Maintenance':'Online'} ok={!controls.maintenance_mode} detail={`v${controls.app_version}`}/><HealthCard icon={<WalletCards size={18}/>} title="Prodaja" value={controls.sales_open?'Otvorena':'Zatvorena'} ok={controls.sales_open} detail={`${pending.length} čeka uplatu`}/><HealthCard icon={<WandSparkles size={18}/>} title="AI Food Image" value={aiConfigured&&controls.ai_images_enabled?'Spreman':aiConfigured?'Pauziran':'Nije podešen'} ok={aiConfigured&&controls.ai_images_enabled} detail={`${monthAi} generisano ovog meseca`}/><HealthCard icon={<Bell size={18}/>} title="Outbox" value={`${queued.length} čeka`} ok={queued.length===0} detail={`${outbox.length} poruka ukupno`}/></section>
      {expiring.length>0&&<section className="admin-alert-strip"><Bell size={18}/><div><strong>{expiring.length} paketa ističe u narednih 7 dana</strong><span>Otvori Kupci i produži pristup ili pošalji podsetnik.</span></div><button onClick={()=>setView('customers')}>Otvori kupce</button></section>}
      <div className="admin-overview-grid"><QuickSale profiles={profiles} plans={plans} form={sale} setForm={setSale} go={grant} working={working}/><LicenseMaker plans={plans} form={license} setForm={setLicense} go={makeLicense} generated={generated} copy={copy} working={working}/></div>
      <section className="admin-panel"><Head e="POSLEDNJE NARUDŽBINE" t="Prodajni tok" side={<button className="secondary" onClick={exportSales}><Download size={14}/> CSV prodaje</button>}/><Orders rows={orders.slice(0,8)} profiles={profiles} paid={paid} cancel={cancel} refund={refund} working={working}/></section></>}

    {view==='customers'&&<section className="admin-panel"><div className="admin-panel-head admin-customers-head"><div><p className="eyebrow">KUPCI I KORIŠĆENJE</p><h2>Svi nalozi pod tvojom kontrolom</h2></div><div className="admin-head-actions"><button className="secondary" onClick={exportCustomers}><Download size={14}/> CSV</button><div className="admin-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Email, restoran, firma..."/></div></div></div><div className="admin-table customer-table owner-customer-table"><div className="admin-table-head"><span>Kupac</span><span>Lokacije</span><span>Paket</span><span>Korišćenje</span><span>Važi do</span><span>Kontrola</span></div>{customers.length?customers.map(p=>{const s=subByUser.get(p.user_id),rs=restaurantsByUser.get(p.user_id)||[],pc=postCountByUser.get(p.user_id)||0,ac=aiCountByUser.get(p.user_id)||0;return <div className="admin-table-row" key={p.user_id}><div><strong>{p.full_name||p.email}</strong><small>{p.email}{p.company?` · ${p.company}`:''}</small></div><div><strong>{rs.length}</strong><small>{rs.map(r=>r.name).slice(0,2).join(' · ')||'nije dodat restoran'}</small></div><div>{s?<><span className={`status ${s.status}`}>{s.status}</span><small>{s.sales_plans?.name||'custom'}</small></>:<span className="status pending">bez paketa</span>}</div><div className="owner-usage-mini"><span><Sparkles size={12}/>{pc} objava</span><span><ImageIcon size={12}/>{ac} AI slika</span></div><div><strong>{s?.expires_at?new Date(s.expires_at).toLocaleDateString('sr-RS'):s?'bez isteka':'—'}</strong>{s?.expires_at&&daysTo(s.expires_at)<=7&&daysTo(s.expires_at)>=0?<small className="expires-soon">još {daysTo(s.expires_at)} dana</small>:null}</div><div className="admin-row-actions"><button onClick={()=>{setNoteTarget(p);setNoteBody('')}}><Mail size={13}/> Poruka</button>{s&&<><button onClick={()=>void extend(s,30)}>+30d</button><button onClick={()=>void extend(s,365)}>+1g</button>{s.status==='suspended'?<button onClick={()=>void setSubStatus(s,'active')}><CheckCircle2 size={13}/> Aktiviraj</button>:<button className="danger-soft" onClick={()=>void setSubStatus(s,'suspended')}><Ban size={13}/> Suspenduj</button>}</>}</div></div>}):<div className="admin-empty">Još nema kupaca.</div>}</div></section>}

    {view==='sales'&&<section className="admin-panel"><Head e="PRODAJA" t="Narudžbine, uplate i refundi" side={<div className="admin-head-actions"><span className="admin-counter">{pending.length} čeka</span><button className="secondary" onClick={exportSales}><Download size={14}/> CSV</button></div>}/><Orders rows={orders} profiles={profiles} paid={paid} cancel={cancel} refund={refund} working={working}/></section>}

    {view==='licenses'&&<div className="admin-two-column"><LicenseMaker plans={plans} form={license} setForm={setLicense} go={makeLicense} generated={generated} copy={copy} working={working}/><section className="admin-panel"><Head e="IZDATE LICENCE" t="Kodovi i status"/><div className="license-list">{licenses.length?licenses.map(x=><div className="license-row-admin" key={x.id}><div><strong>•••• {x.code_last4}</strong><span>{x.sales_plans?.name||'Paket'} · {x.assigned_email||'bez email ograničenja'}</span></div><div><span className={`status ${x.status}`}>{x.status}</span><small>{x.use_count}/{x.max_uses} · {x.sale_amount??0} {x.currency}</small></div>{x.status==='active'&&<button className="danger-soft" onClick={()=>void revoke(x)}>Opozovi</button>}</div>):<div className="admin-empty">Nema izdatih licenci.</div>}</div></section></div>}

    {view==='plans'&&<section className="admin-panel"><Head e="PAKETI, CENE I FUNKCIJE" t="Ti određuješ šta kupac dobija"/><div className="owner-plan-grid">{plans.map(p=><PlanEditor key={p.id} plan={p} onSave={savePlan}/>)}</div></section>}

    {view==='system'&&<div className="owner-system-grid"><section className="admin-panel"><Head e="GLOBALNA KONTROLA" t="Aplikacija i prodaja"/><div className="owner-switch-stack"><BigToggle icon={<Power size={18}/>} title="Maintenance mode" detail="Kupcima blokiraš rad dok radiš kritične izmene." value={controls.maintenance_mode} onChange={v=>setControls({...controls,maintenance_mode:v})} danger/><BigToggle icon={<WalletCards size={18}/>} title="Prodaja otvorena" detail="Server-side blokira kreiranje novih narudžbina kada je ugašeno." value={controls.sales_open} onChange={v=>setControls({...controls,sales_open:v})}/><BigToggle icon={<UsersRound size={18}/>} title="Registracije otvorene" detail="Centralni prekidač za nove naloge." value={controls.signup_open} onChange={v=>setControls({...controls,signup_open:v})}/><BigToggle icon={<ImageIcon size={18}/>} title="AI fotografije" detail="Globalno uključuje ili pauzira AI food generation." value={controls.ai_images_enabled} onChange={v=>setControls({...controls,ai_images_enabled:v})}/><BigToggle icon={<Megaphone size={18}/>} title="Obaveštenje u aplikaciji" detail="Prikaži važnu poruku svim korisnicima." value={controls.announcement_enabled} onChange={v=>setControls({...controls,announcement_enabled:v})}/></div><div className="admin-form-grid owner-system-fields"><label>Verzija<input value={controls.app_version} onChange={e=>setControls({...controls,app_version:e.target.value})}/></label><label>WhatsApp podrška<input value={controls.support_whatsapp||''} onChange={e=>setControls({...controls,support_whatsapp:e.target.value})} placeholder="+381..."/></label><label className="span-2">Maintenance poruka<textarea rows={3} value={controls.maintenance_message||''} onChange={e=>setControls({...controls,maintenance_message:e.target.value})} placeholder="Radimo kratko održavanje. Vraćamo se uskoro."/></label><label className="span-2">Globalno obaveštenje<textarea rows={3} value={controls.announcement_text||''} onChange={e=>setControls({...controls,announcement_text:e.target.value})} placeholder="Nova funkcija: Creative AI je dostupan..."/></label><label>Tip poruke<select value={controls.announcement_tone} onChange={e=>setControls({...controls,announcement_tone:e.target.value as AppControls['announcement_tone']})}><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option></select></label></div><button className="primary" onClick={saveSystem} disabled={working}><Save size={16}/> Sačuvaj sistem</button></section>
      <section className="admin-panel"><Head e="AI PROVIDER" t="Food Image Engine"/><div className={`owner-ai-status ${aiConfigured&&controls.ai_images_enabled?'ready':''}`}><span><WandSparkles size={23}/></span><div><strong>{aiConfigured?'OpenAI ključ je podešen':'AI ključ nije podešen'}</strong><small>{aiConfigured?(controls.ai_images_enabled?'Generisanje slika je spremno.':'Ključ postoji, ali si AI globalno pauzirao.'):'Unesi ključ jednom. Čuva se server-side u Supabase Vault-u.'}</small></div></div><label className="owner-ai-key">OpenAI API ključ<input type="password" autoComplete="new-password" value={aiKey} onChange={e=>setAiKey(e.target.value)} placeholder={aiConfigured?'Novi sk-… samo ako menjaš postojeći':'sk-…'}/></label><button className="secondary full" onClick={saveAiKey} disabled={working||!aiKey.trim()}><KeyRound size={15}/>{aiConfigured?'Promeni AI ključ':'Aktiviraj AI'}</button><div className="owner-ai-usage"><div><span>Ovog meseca</span><strong>{monthAi}</strong><small>AI food slika</small></div><div><span>Ukupno</span><strong>{creative.length}</strong><small>sačuvanih asseta</small></div></div></section>
      {settings&&<section className="admin-panel owner-sales-settings"><Head e="PRODAVAC I NAPLATA" t="Podaci koji idu kupcu"/><div className="admin-form-grid"><F l="Naziv u aplikaciji" v={settings.company_name} c={v=>setSettings({...settings,company_name:v})}/><F l="Pravni naziv" v={settings.legal_name||''} c={v=>setSettings({...settings,legal_name:v})}/><F l="PIB" v={settings.tax_id||''} c={v=>setSettings({...settings,tax_id:v})}/><F l="Matični broj" v={settings.company_number||''} c={v=>setSettings({...settings,company_number:v})}/><F l="Adresa" v={settings.address||''} c={v=>setSettings({...settings,address:v})}/><F l="Sales email" v={settings.sales_email||''} c={v=>setSettings({...settings,sales_email:v})}/><F l="Support email" v={settings.support_email||''} c={v=>setSettings({...settings,support_email:v})}/><F l="Banka" v={settings.bank_name||''} c={v=>setSettings({...settings,bank_name:v})}/><F l="Broj računa" v={settings.bank_account||''} c={v=>setSettings({...settings,bank_account:v})}/><F l="Model" v={settings.payment_model||''} c={v=>setSettings({...settings,payment_model:v})}/><F l="PayPal link" v={settings.paypal_url||''} c={v=>setSettings({...settings,paypal_url:v})}/><F l="Uslovi korišćenja URL" v={settings.terms_url||''} c={v=>setSettings({...settings,terms_url:v})}/><label className="span-2">Instrukcije za uplatu<textarea rows={4} value={settings.bank_instructions||''} onChange={e=>setSettings({...settings,bank_instructions:e.target.value})}/></label><div className="sales-method-toggles span-2"><SmallToggle l="Uplata na račun" v={settings.allow_bank_transfer} c={v=>setSettings({...settings,allow_bank_transfer:v})}/><SmallToggle l="Faktura" v={settings.allow_invoice} c={v=>setSettings({...settings,allow_invoice:v})}/><SmallToggle l="PayPal" v={settings.allow_paypal} c={v=>setSettings({...settings,allow_paypal:v})}/><SmallToggle l="Kartica" v={settings.allow_card} c={v=>setSettings({...settings,allow_card:v})}/><SmallToggle l="Trial" v={settings.trial_enabled} c={v=>setSettings({...settings,trial_enabled:v})}/></div></div><button className="primary" onClick={saveSales} disabled={working}><Save size={16}/> Sačuvaj prodaju</button></section>}
    </div>}

    {view==='messages'&&<section className="admin-panel"><Head e="EMAIL / IN-APP OUTBOX" t="Sistemske i ručne poruke" side={<span className="admin-counter">{queued.length} čeka</span>}/><div className="outbox-list">{outbox.length?outbox.map(x=><div className={`outbox-row ${x.delivery_status}`} key={x.id}><div><strong>{x.subject}</strong><span>{x.recipient_email||'bez emaila'} · {new Date(x.created_at).toLocaleString('sr-RS')}</span><p>{x.body}</p></div><span className={`status ${x.delivery_status}`}>{x.delivery_status}</span><div className="admin-row-actions"><button onClick={()=>copy(`${x.subject}\n\n${x.body}`)}><Copy size={13}/> Kopiraj</button>{x.delivery_status==='queued'&&<><button onClick={()=>void markOut(x,'sent')}><CheckCircle2 size={13}/> Poslato</button><button className="danger-soft" onClick={()=>void markOut(x,'dismissed')}>Skloni</button></>}</div></div>):<div className="admin-empty">Outbox je prazan.</div>}</div></section>}

    {view==='audit'&&<section className="admin-panel"><Head e="AUDIT LOG" t="Koja OWNER akcija je urađena i kada"/><div className="audit-list">{audit.length?audit.map(x=><div className="audit-row" key={x.id}><span className="audit-dot"/><div><strong>{auditLabel(x.action)}</strong><span>{x.entity_type}{x.entity_id?` · ${x.entity_id}`:''}</span></div><code>{compact(x.details)}</code><time>{new Date(x.created_at).toLocaleString('sr-RS')}</time></div>):<div className="admin-empty">Audit je prazan.</div>}</div></section>}

    {noteTarget&&<div className="modal-backdrop" onMouseDown={()=>setNoteTarget(null)}><div className="modal-card admin-note-modal" onMouseDown={e=>e.stopPropagation()}><p className="eyebrow">PORUKA KUPCU</p><h2>{noteTarget.email}</h2><label>Naslov<input value={noteSubject} onChange={e=>setNoteSubject(e.target.value)}/></label><label>Poruka<textarea rows={6} value={noteBody} onChange={e=>setNoteBody(e.target.value)}/></label><div className="modal-actions"><button className="secondary" onClick={()=>setNoteTarget(null)}>Otkaži</button><button className="primary" onClick={sendNote} disabled={working}><Mail size={15}/> Dodaj poruku</button></div></div></div>}
  </div>
}

function Tab({a,f,i,l,c}:{a:boolean;f:()=>void;i:ReactNode;l:string;c?:number}){return <button className={a?'active':''} onClick={f}>{i}{l}{c?<b>{c}</b>:null}</button>}
function Metric({i,l,v}:{i:ReactNode;l:string;v:string|number}){return <div className="admin-metric"><span>{i}</span><div><small>{l}</small><strong>{v}</strong></div></div>}
function Head({e,t,side}:{e:string;t:string;side?:ReactNode}){return <div className="admin-panel-head"><div><p className="eyebrow">{e}</p><h2>{t}</h2></div>{side}</div>}
function HealthCard({icon,title,value,detail,ok}:{icon:ReactNode;title:string;value:string;detail:string;ok:boolean}){return <div className={`owner-health ${ok?'ok':''}`}><span>{icon}</span><div><small>{title}</small><strong>{value}</strong><p>{detail}</p></div><i/></div>}
function BigToggle({icon,title,detail,value,onChange,danger=false}:{icon:ReactNode;title:string;detail:string;value:boolean;onChange:(v:boolean)=>void;danger?:boolean}){return <button type="button" className={`owner-big-toggle ${value?'on':''} ${danger?'danger-mode':''}`} onClick={()=>onChange(!value)}><span>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><b>{value?<Eye size={15}/>:<EyeOff size={15}/>} {value?'UKLJUČENO':'ISKLJUČENO'}</b></button>}
function F({l,v,c}:{l:string;v:string;c:(v:string)=>void}){return <label>{l}<input value={v} onChange={e=>c(e.target.value)}/></label>}
function SmallToggle({l,v,c}:{l:string;v:boolean;c:(v:boolean)=>void}){return <label className={`sales-toggle ${v?'on':''}`}><input type="checkbox" checked={v} onChange={e=>c(e.target.checked)}/><span/><b>{l}</b></label>}

function QuickSale({profiles,plans,form,setForm,go,working}:{profiles:CustomerProfile[];plans:SalesPlan[];form:SaleForm;setForm:(v:SaleForm)=>void;go:()=>void;working:boolean}){return <section className="admin-panel"><Head e="BRZA PRODAJA" t="Aktiviraj kupca odmah"/><div className="admin-form-grid"><label>Kupac<select value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}><option value="">Izaberi</option>{profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.email}</option>)}</select></label><label>Paket<select value={form.planId} onChange={e=>setForm({...form,planId:e.target.value})}><option value="">Izaberi</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name} · {p.price} {p.currency}</option>)}</select></label><label>Dana<input type="number" min="1" value={form.days} onChange={e=>setForm({...form,days:e.target.value})}/></label><label>Naplaćeno<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Način<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{methods.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Napomena<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button className="primary full" onClick={go} disabled={working}><CheckCircle2 size={16}/> Aktiviraj i evidentiraj</button></section>}
function LicenseMaker({plans,form,setForm,go,generated,copy,working}:{plans:SalesPlan[];form:LicenseForm;setForm:(v:LicenseForm)=>void;go:()=>void;generated:Generated|null;copy:(v:string)=>void;working:boolean}){return <section className="admin-panel"><Head e="AKTIVACIONI KOD" t="Prodaj licencu"/><div className="admin-form-grid"><label>Paket<select value={form.planId} onChange={e=>setForm({...form,planId:e.target.value})}><option value="">Izaberi</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Dana<input type="number" min="1" value={form.days} onChange={e=>setForm({...form,days:e.target.value})}/></label><label>Cena<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Način<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{methods.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Napomena<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button className="primary full" onClick={go} disabled={working}><KeyRound size={16}/> Generiši licencu</button>{generated&&<div className="generated-license"><span>KOPIRAJ SADA</span><strong>{generated.code}</strong><small>{generated.plan}</small><button onClick={()=>copy(generated.code)}><Copy size={15}/> Kopiraj</button></div>}</section>}
function Orders({rows,profiles,paid,cancel,refund,working}:{rows:SalesOrder[];profiles:CustomerProfile[];paid:(o:SalesOrder)=>void;cancel:(o:SalesOrder)=>void;refund:(o:SalesOrder)=>void;working:boolean}){const map=new Map(profiles.map(p=>[p.user_id,p]));return <div className="admin-table orders-table orders-table-v2"><div className="admin-table-head"><span>Narudžbina</span><span>Kupac</span><span>Paket</span><span>Iznos</span><span>Status</span><span>Akcija</span></div>{rows.length?rows.map(o=><div className="admin-table-row" key={o.id}><div><strong>{o.order_number}</strong><small>{new Date(o.created_at).toLocaleString('sr-RS')} · {o.payment_reference||o.order_number}</small></div><div><strong>{map.get(o.user_id)?.email||'Kupac'}</strong><small>{o.payment_method}</small></div><div><strong>{o.sales_plans?.name||'—'}</strong><small>{o.due_at?`rok ${new Date(o.due_at).toLocaleDateString('sr-RS')}`:''}</small></div><strong>{o.amount} {o.currency}</strong><span className={`status ${o.status}`}>{o.status}</span><div className="order-admin-actions">{o.status==='pending'&&<><button className="paid-button" disabled={working} onClick={()=>paid(o)}>Uplata primljena</button><button className="danger-soft" onClick={()=>cancel(o)}>Otkaži</button></>}{o.status==='paid'&&<button className="refund-button" onClick={()=>refund(o)}>Refund</button>}</div></div>):<div className="admin-empty">Nema narudžbina.</div>}</div>}
function PlanEditor({plan,onSave}:{plan:SalesPlan;onSave:(p:SalesPlan,patch:{price:number;monthly_generation_limit:number;max_restaurants:number;trial_days:number;active:boolean;public:boolean;features:Record<string,unknown>})=>void}){
  const [price,setPrice]=useState(Number(plan.price)),[limit,setLimit]=useState(plan.monthly_generation_limit),[max,setMax]=useState(plan.max_restaurants),[trial,setTrial]=useState(plan.trial_days)
  const [ai,setAi]=useState(Number(plan.features?.ai_images_monthly||0)),[weekly,setWeekly]=useState(Number(plan.features?.weekly_posts||5)),[campaigns,setCampaigns]=useState(Boolean(plan.features?.campaigns)),[pack,setPack]=useState(Boolean(plan.features?.campaign_pack)),[active,setActive]=useState(plan.active),[isPublic,setPublic]=useState(plan.public)
  useEffect(()=>{setPrice(Number(plan.price));setLimit(plan.monthly_generation_limit);setMax(plan.max_restaurants);setTrial(plan.trial_days);setAi(Number(plan.features?.ai_images_monthly||0));setWeekly(Number(plan.features?.weekly_posts||5));setCampaigns(Boolean(plan.features?.campaigns));setPack(Boolean(plan.features?.campaign_pack));setActive(plan.active);setPublic(plan.public)},[plan])
  const save=()=>onSave(plan,{price,monthly_generation_limit:limit,max_restaurants:max,trial_days:trial,active,public:isPublic,features:{...plan.features,ai_images_monthly:ai,weekly_posts:weekly,campaigns,campaign_pack:pack,creative_advisor:true,template_library:true,visual_studio:true,publish_center:true,brand_kit:true}})
  return <article className={`owner-plan-card ${active?'':'disabled'}`}><div className="owner-plan-head"><div><span>{plan.billing_interval}</span><b>{plan.code}</b></div><div><button className={active?'on':''} onClick={()=>setActive(!active)}>{active?'AKTIVAN':'UGAŠEN'}</button><button className={isPublic?'on':''} onClick={()=>setPublic(!isPublic)}>{isPublic?'JAVAN':'SKRIVEN'}</button></div></div><h3>{plan.name}</h3><p>{plan.description}</p><div className="owner-plan-fields"><label>Cena<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label><label>Objava/mes<input type="number" min="0" value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><label>Restorana<input type="number" min="1" value={max} onChange={e=>setMax(Number(e.target.value))}/></label><label>Trial dana<input type="number" min="0" max="90" value={trial} onChange={e=>setTrial(Number(e.target.value))}/></label><label>AI slika/mes<input type="number" min="0" value={ai} onChange={e=>setAi(Number(e.target.value))}/></label><label>Objava/nedelja<input type="number" min="1" max="14" value={weekly} onChange={e=>setWeekly(Number(e.target.value))}/></label></div><div className="owner-feature-toggles"><SmallToggle l="Campaigns" v={campaigns} c={setCampaigns}/><SmallToggle l="Campaign Pack" v={pack} c={setPack}/></div><button className="primary full" onClick={save}><Save size={14}/> Sačuvaj paket</button></article>
}
function daysTo(v:string){return Math.ceil((new Date(v).getTime()-Date.now())/86400000)}
function sameMonth(value:string,date:Date){const d=new Date(value);return d.getMonth()===date.getMonth()&&d.getFullYear()===date.getFullYear()}
function auditLabel(v:string){return({order_paid:'Uplata potvrđena',order_refunded:'Refund',access_granted:'Ručna aktivacija',license_created:'Licenca kreirana',license_redeemed:'Licenca aktivirana',trial_started:'Trial',customer_note_queued:'Poruka kupcu',housekeeping:'Housekeeping',ai_provider_key_updated:'AI ključ promenjen'} as Record<string,string>)[v]||v}
function compact(v:Record<string,unknown>){const s=JSON.stringify(v);return s.length>120?`${s.slice(0,117)}…`:s}
function downloadCsv(name:string,rows:string[][]){const q=(v:string)=>`"${String(v).replaceAll('"','""')}"`;downloadText(name,'\ufeff'+rows.map(r=>r.map(q).join(';')).join('\n'),'text/csv;charset=utf-8')}
function downloadText(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
