import { useEffect, useMemo, useState } from 'react'
import { BadgePercent, CalendarDays, Copy, Download, Plus, RefreshCw, Save, Trash2 } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { PromoCode, SalesPlan } from '../types'

type Draft={code:string;description:string;discount_type:'percent'|'fixed';discount_value:string;plan_id:string;max_uses:string;expires_at:string}
const fresh:Draft={code:'',description:'',discount_type:'percent',discount_value:'20',plan_id:'',max_uses:'',expires_at:''}

export function PromoCodesAdmin({setNotice}:{setNotice:(v:string)=>void}){
  const[codes,setCodes]=useState<PromoCode[]>([]),[plans,setPlans]=useState<SalesPlan[]>([]),[draft,setDraft]=useState<Draft>(fresh),[working,setWorking]=useState(false)
  useEffect(()=>{void load()},[])
  async function load(){setWorking(true);const[a,b]=await Promise.all([supabase.from('promo_codes').select('*, sales_plans(*)').order('created_at',{ascending:false}),supabase.from('sales_plans').select('*').order('sort_order')]);if(a.error||b.error)setNotice((a.error||b.error)?.message||'Greška');setCodes((a.data||[]) as PromoCode[]);setPlans((b.data||[]) as SalesPlan[]);setWorking(false)}
  const active=useMemo(()=>codes.filter(c=>c.active&&(!c.expires_at||new Date(c.expires_at).getTime()>Date.now())).length,[codes])
  async function create(){const code=draft.code.trim().toUpperCase().replace(/\s+/g,'-');const value=Number(draft.discount_value);if(code.length<3||!Number.isFinite(value)||value<=0){setNotice('Upiši ispravan kod i vrednost popusta.');return}if(draft.discount_type==='percent'&&value>100){setNotice('Procentualni popust ne može biti veći od 100%.');return}setWorking(true);const{data:user}=await supabase.auth.getUser();const{error}=await supabase.from('promo_codes').insert({code,description:draft.description.trim()||null,discount_type:draft.discount_type,discount_value:value,plan_id:draft.plan_id||null,max_uses:draft.max_uses?Number(draft.max_uses):null,expires_at:draft.expires_at?new Date(`${draft.expires_at}T23:59:59`).toISOString():null,active:true,created_by:user.user?.id||null});if(error)setNotice(error.message);else{setNotice(`Promo kod ${code} je aktivan.`);setDraft(fresh);await load()}setWorking(false)}
  async function toggle(row:PromoCode){const{error}=await supabase.from('promo_codes').update({active:!row.active,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)setNotice(error.message);else await load()}
  async function remove(row:PromoCode){if(!confirm(`Obriši promo kod ${row.code}?`))return;const{error}=await supabase.from('promo_codes').delete().eq('id',row.id);if(error)setNotice(error.message);else{setNotice('Promo kod je obrisan.');await load()}}
  function generate(){const tail=Math.random().toString(36).slice(2,7).toUpperCase();setDraft({...draft,code:`AUTO-${tail}`})}
  function copy(v:string){navigator.clipboard.writeText(v).then(()=>setNotice('Kod je kopiran.')).catch(()=>setNotice('Browser nije dozvolio kopiranje.'))}
  function exportCsv(){const q=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;const rows=[['kod','tip','vrednost','paket','koriscenja','max','aktivan','istice'],...codes.map(c=>[c.code,c.discount_type,c.discount_value,c.sales_plans?.name||'svi',c.use_count,c.max_uses??'',c.active?'da':'ne',c.expires_at||''])];const csv='\ufeff'+rows.map(r=>r.map(q).join(';')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='restaurant-autopilot-promo-kodovi.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <div className="promo-admin-page"><header className="promo-admin-head"><div><p className="eyebrow">OWNER · PRODAJA</p><h1>Promo kodovi</h1><p>Popusti za kampanje, partnere, prve kupce i posebne ponude.</p></div><div><span className="promo-stat"><b>{active}</b> aktivnih</span><button className="secondary" onClick={()=>void load()} disabled={working}><RefreshCw size={15}/> Osveži</button><button className="secondary" onClick={exportCsv}><Download size={15}/> CSV</button></div></header>
    <div className="promo-admin-grid"><section className="admin-panel promo-create-card"><div className="admin-panel-head"><div><p className="eyebrow">NOVI KOD</p><h2>Kreiraj popust</h2></div><BadgePercent size={22}/></div><div className="admin-form-grid"><label>Kod<div className="promo-code-input"><input value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value.toUpperCase()})} placeholder="START20"/><button type="button" onClick={generate}>Generiši</button></div></label><label>Tip<select value={draft.discount_type} onChange={e=>setDraft({...draft,discount_type:e.target.value as Draft['discount_type']})}><option value="percent">Procenat %</option><option value="fixed">Fiksni iznos</option></select></label><label>Vrednost<input type="number" min="1" step="0.01" value={draft.discount_value} onChange={e=>setDraft({...draft,discount_value:e.target.value})}/></label><label>Paket<select value={draft.plan_id} onChange={e=>setDraft({...draft,plan_id:e.target.value})}><option value="">Svi paketi</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Max korišćenja<input type="number" min="1" value={draft.max_uses} onChange={e=>setDraft({...draft,max_uses:e.target.value})} placeholder="bez limita"/></label><label>Važi do<input type="date" value={draft.expires_at} onChange={e=>setDraft({...draft,expires_at:e.target.value})}/></label><label className="span-2">Opis<input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="20% za prve kupce"/></label></div><button className="primary full" onClick={create} disabled={working}><Plus size={16}/> Kreiraj promo kod</button></section>
      <section className="admin-panel promo-list-card"><div className="admin-panel-head"><div><p className="eyebrow">KODOVI</p><h2>Aktivni i arhiva</h2></div><CalendarDays size={20}/></div><div className="promo-code-list">{codes.length?codes.map(row=>{const expired=Boolean(row.expires_at&&new Date(row.expires_at).getTime()<=Date.now());return <div className={`promo-code-row ${!row.active||expired?'inactive':''}`} key={row.id}><div className="promo-code-mark"><strong>{row.code}</strong><button onClick={()=>copy(row.code)} title="Kopiraj"><Copy size={13}/></button><span>{row.discount_type==='percent'?`${row.discount_value}%`:`${row.discount_value} €`} · {row.sales_plans?.name||'svi paketi'}</span></div><div className="promo-code-usage"><span>{row.use_count}{row.max_uses?` / ${row.max_uses}`:''}</span><small>korišćenja</small></div><div className="promo-code-expiry"><span>{row.expires_at?new Date(row.expires_at).toLocaleDateString('sr-RS'):'bez isteka'}</span><small>{expired?'istekao':row.active?'aktivan':'pauziran'}</small></div><div className="promo-code-actions"><button onClick={()=>void toggle(row)}>{row.active?'Pauziraj':'Aktiviraj'}</button><button className="danger-soft" onClick={()=>void remove(row)}><Trash2 size={13}/></button></div></div>}):<div className="admin-empty">Još nema promo kodova.</div>}</div></section></div>
  </div>
}
