import { type ReactNode, useEffect, useMemo, useState } from 'react'
import { BadgeEuro, Ban, Bell, BookOpenCheck, CheckCircle2, CircleDollarSign, Copy, FileDown, KeyRound, Mail, RefreshCw, Save, Search, Settings2, ShieldCheck, Store, TicketCheck, Undo2, UsersRound, WalletCards, Zap } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { AdminAuditLog, CustomerProfile, CustomerSubscription, LicenseCodeRow, NotificationOutbox, SalesOrder, SalesPlan, SalesSettings } from '../types'

type View='overview'|'customers'|'orders'|'licenses'|'plans'|'outbox'|'audit'|'settings'
type RestaurantLite={id:string;owner_id:string;name:string;city:string|null;created_at:string}
type SaleForm={userId:string;planId:string;days:string;amount:string;paymentMethod:string;note:string}
type LicenseForm={planId:string;email:string;days:string;amount:string;paymentMethod:string;note:string}
type Generated={id:string;code:string;plan:string;assigned_email:string|null}
const methods=[['manual','Ručno / ostalo'],['bank_transfer','Uplata na račun'],['invoice','Predračun / faktura'],['paypal','PayPal'],['card','Kartica'],['cash','Keš']] as const
const freshSale:SaleForm={userId:'',planId:'',days:'',amount:'',paymentMethod:'manual',note:''}
const freshLicense:LicenseForm={planId:'',email:'',days:'',amount:'',paymentMethod:'manual',note:''}

export function SuperAdmin({onCloseApp,setNotice}:{onCloseApp?:()=>void;setNotice:(v:string)=>void}){
 const[view,setView]=useState<View>('overview'),[profiles,setProfiles]=useState<CustomerProfile[]>([]),[restaurants,setRestaurants]=useState<RestaurantLite[]>([]),[plans,setPlans]=useState<SalesPlan[]>([]),[subs,setSubs]=useState<CustomerSubscription[]>([]),[orders,setOrders]=useState<SalesOrder[]>([]),[licenses,setLicenses]=useState<LicenseCodeRow[]>([]),[settings,setSettings]=useState<SalesSettings|null>(null),[outbox,setOutbox]=useState<NotificationOutbox[]>([]),[audit,setAudit]=useState<AdminAuditLog[]>([])
 const[working,setWorking]=useState(false),[search,setSearch]=useState(''),[sale,setSale]=useState<SaleForm>(freshSale),[license,setLicense]=useState<LicenseForm>(freshLicense),[generated,setGenerated]=useState<Generated|null>(null),[noteTarget,setNoteTarget]=useState<CustomerProfile|null>(null),[noteSubject,setNoteSubject]=useState('Restaurant Autopilot'),[noteBody,setNoteBody]=useState('')
 useEffect(()=>{void load(true)},[])
 async function load(housekeeping=false){setWorking(true);if(housekeeping)await supabase.rpc('admin_housekeeping');const[a,b,c,d,e,f,g,h,i]=await Promise.all([supabase.from('customer_profiles').select('*').order('created_at',{ascending:false}),supabase.from('restaurants').select('id,owner_id,name,city,created_at').order('created_at',{ascending:false}),supabase.from('sales_plans').select('*').order('sort_order'),supabase.from('customer_subscriptions').select('*, sales_plans(*)').order('created_at',{ascending:false}),supabase.from('sales_orders').select('*, sales_plans(*)').order('created_at',{ascending:false}),supabase.from('license_codes').select('*, sales_plans(*)').order('created_at',{ascending:false}).limit(150),supabase.from('sales_settings').select('*').eq('id',1).maybeSingle(),supabase.from('notification_outbox').select('*').order('created_at',{ascending:false}).limit(150),supabase.from('admin_audit_log').select('*').order('created_at',{ascending:false}).limit(200)]);const err=a.error||b.error||c.error||d.error||e.error||f.error||g.error||h.error||i.error;if(err)setNotice(err.message);setProfiles((a.data||[]) as CustomerProfile[]);setRestaurants((b.data||[]) as RestaurantLite[]);setPlans((c.data||[]) as SalesPlan[]);setSubs((d.data||[]) as CustomerSubscription[]);setOrders((e.data||[]) as SalesOrder[]);setLicenses((f.data||[]) as LicenseCodeRow[]);setSettings((g.data||null) as SalesSettings|null);setOutbox((h.data||[]) as NotificationOutbox[]);setAudit((i.data||[]) as AdminAuditLog[]);setWorking(false)}
 const active=useMemo(()=>subs.filter(s=>['active','trialing'].includes(s.status)&&(!s.expires_at||new Date(s.expires_at).getTime()>Date.now())),[subs]),pending=useMemo(()=>orders.filter(o=>o.status==='pending'),[orders]),revenue=useMemo(()=>orders.filter(o=>o.status==='paid').reduce((n,o)=>n+Number(o.amount||0),0),[orders]),monthRevenue=useMemo(()=>orders.filter(o=>o.status==='paid'&&new Date(o.paid_at||o.created_at).getMonth()===new Date().getMonth()&&new Date(o.paid_at||o.created_at).getFullYear()===new Date().getFullYear()).reduce((n,o)=>n+Number(o.amount||0),0),[orders]),expiring=useMemo(()=>active.filter(s=>s.expires_at&&daysTo(s.expires_at)<=7&&daysTo(s.expires_at)>=0),[active]),queued=useMemo(()=>outbox.filter(x=>x.delivery_status==='queued'),[outbox])
 const subByUser=useMemo(()=>{const m=new Map<string,CustomerSubscription>();subs.forEach(s=>{if(!m.has(s.user_id))m.set(s.user_id,s)});return m},[subs]),restByUser=useMemo(()=>{const m=new Map<string,RestaurantLite>();restaurants.forEach(r=>{if(!m.has(r.owner_id))m.set(r.owner_id,r)});return m},[restaurants]),profileByUser=useMemo(()=>new Map(profiles.map(p=>[p.user_id,p])),[profiles]),customers=useMemo(()=>{const q=search.toLowerCase().trim();return q?profiles.filter(p=>`${p.email} ${p.full_name||''} ${p.company||''} ${restByUser.get(p.user_id)?.name||''}`.toLowerCase().includes(q)):profiles},[profiles,search,restByUser])
 async function paid(o:SalesOrder){setWorking(true);const{error}=await supabase.rpc('admin_mark_order_paid',{p_order_id:o.id,p_admin_note:'Potvrđeno iz Superadmin panela'});if(error)setNotice(error.message);else{setNotice(`${o.order_number}: uplata potvrđena i paket aktiviran.`);await load()}setWorking(false)}
 async function cancel(o:SalesOrder){if(!confirm(`Otkaži ${o.order_number}?`))return;const{error}=await supabase.from('sales_orders').update({status:'cancelled',admin_note:'Otkazano iz Superadmin panela'}).eq('id',o.id);if(error)setNotice(error.message);else{setNotice('Narudžbina je otkazana.');await load()}}
 async function refund(o:SalesOrder){if(!confirm(`Refund ${o.order_number} i zatvori povezani pristup?`))return;setWorking(true);const{error}=await supabase.rpc('admin_refund_order',{p_order_id:o.id,p_suspend_access:true,p_note:'Refund iz Superadmin panela'});if(error)setNotice(error.message);else{setNotice('Refund evidentiran; pristup je zatvoren.');await load()}setWorking(false)}
 async function grant(){if(!sale.userId||!sale.planId){setNotice('Izaberi kupca i paket.');return}setWorking(true);const{error}=await supabase.rpc('admin_grant_access',{p_user_id:sale.userId,p_plan_id:sale.planId,p_days:sale.days?Number(sale.days):null,p_payment_method:sale.paymentMethod,p_amount:sale.amount?Number(sale.amount):null,p_note:sale.note||null});if(error)setNotice(error.message);else{setNotice('Prodaja evidentirana i paket aktiviran.');setSale(freshSale);await load()}setWorking(false)}
 async function makeLicense(){if(!license.planId){setNotice('Izaberi paket.');return}setWorking(true);const{data,error}=await supabase.rpc('admin_create_license_code',{p_plan_id:license.planId,p_duration_days:license.days?Number(license.days):null,p_assigned_email:license.email||null,p_sale_amount:license.amount?Number(license.amount):null,p_payment_method:license.paymentMethod,p_note:license.note||null});if(error)setNotice(error.message);else{setGenerated(data as Generated);setNotice('Licenca je napravljena. Kopiraj puni kod sada.');setLicense(freshLicense);await load()}setWorking(false)}
 async function subStatus(s:CustomerSubscription,status:CustomerSubscription['status']){const{error}=await supabase.from('customer_subscriptions').update({status}).eq('id',s.id);if(error)setNotice(error.message);else await load()}
 async function extend(s:CustomerSubscription,days:number){const d=s.expires_at&&new Date(s.expires_at).getTime()>Date.now()?new Date(s.expires_at):new Date();d.setDate(d.getDate()+days);const{error}=await supabase.from('customer_subscriptions').update({expires_at:d.toISOString(),status:'active'}).eq('id',s.id);if(error)setNotice(error.message);else{setNotice(`Produženo za ${days} dana.`);await load()}}
 async function revoke(x:LicenseCodeRow){const{error}=await supabase.from('license_codes').update({status:'revoked'}).eq('id',x.id);if(error)setNotice(error.message);else await load()}
 async function savePlan(p:SalesPlan,price:number,limit:number,max:number){const{error}=await supabase.from('sales_plans').update({price,monthly_generation_limit:limit,max_restaurants:max}).eq('id',p.id);if(error)setNotice(error.message);else{setNotice(`${p.name} sačuvan.`);await load()}}
 async function togglePlan(p:SalesPlan){const{error}=await supabase.from('sales_plans').update({active:!p.active}).eq('id',p.id);if(error)setNotice(error.message);else await load()}
 async function saveSettings(){if(!settings)return;setWorking(true);const{error}=await supabase.from('sales_settings').update(settings).eq('id',1);if(error)setNotice(error.message);else setNotice('Prodajna podešavanja su sačuvana.');setWorking(false)}
 async function markOut(x:NotificationOutbox,status:'sent'|'dismissed'){const patch=status==='sent'?{delivery_status:'sent',sent_at:new Date().toISOString()}:{delivery_status:'dismissed'};const{error}=await supabase.from('notification_outbox').update(patch).eq('id',x.id);if(error)setNotice(error.message);else await load()}
 async function sendNote(){if(!noteTarget||!noteSubject.trim()||!noteBody.trim()){setNotice('Upiši naslov i poruku.');return}setWorking(true);const{error}=await supabase.rpc('admin_send_note',{p_user_id:noteTarget.user_id,p_subject:noteSubject.trim(),p_body:noteBody.trim()});if(error)setNotice(error.message);else{setNotice('Poruka je dodata kupcu i u outbox.');setNoteTarget(null);setNoteBody('');await load()}setWorking(false)}
 function copy(v:string){navigator.clipboard.writeText(v).then(()=>setNotice('Kopirano.')).catch(()=>setNotice('Browser nije dozvolio kopiranje.'))}
 function exportCsv(){const rows=[['narudzbina','datum','kupac','paket','status','nacin','iznos','valuta','referenca'],...orders.map(o=>[o.order_number,o.created_at,profileByUser.get(o.user_id)?.email||o.user_id,o.sales_plans?.name||'',o.status,o.payment_method,String(o.amount),o.currency,o.payment_reference||''])];downloadCsv('restaurant-autopilot-prodaja.csv',rows);setNotice('Prodaja izvezena u CSV.')}
 return <div className="superadmin-page superadmin-v2"><header className="admin-topbar"><div><span className="admin-shield"><ShieldCheck size={21}/></span><div><p>RESTAURANT AUTOPILOT</p><h1>Owner Superadmin</h1></div></div><div className="admin-top-actions"><span className="admin-live"><i/> OWNER CONTROL</span><button className="secondary" onClick={()=>void load(true)} disabled={working}><RefreshCw size={15}/> Osveži + housekeeping</button>{onCloseApp&&<button className="secondary" onClick={onCloseApp}>Nazad u app</button>}</div></header>
 <nav className="admin-tabs"><Tab a={view==='overview'} f={()=>setView('overview')} i={<Zap size={16}/>} l="Pregled"/><Tab a={view==='customers'} f={()=>setView('customers')} i={<UsersRound size={16}/>} l="Kupci"/><Tab a={view==='orders'} f={()=>setView('orders')} i={<WalletCards size={16}/>} l="Prodaja" c={pending.length}/><Tab a={view==='licenses'} f={()=>setView('licenses')} i={<KeyRound size={16}/>} l="Licence"/><Tab a={view==='plans'} f={()=>setView('plans')} i={<BadgeEuro size={16}/>} l="Paketi"/><Tab a={view==='outbox'} f={()=>setView('outbox')} i={<Bell size={16}/>} l="Outbox" c={queued.length}/><Tab a={view==='audit'} f={()=>setView('audit')} i={<BookOpenCheck size={16}/>} l="Audit"/><Tab a={view==='settings'} f={()=>setView('settings')} i={<Settings2 size={16}/>} l="Podešavanja"/></nav>
 {view==='overview'&&<><section className="admin-metrics admin-metrics-6"><Metric i={<UsersRound size={18}/>} l="Registrovani" v={profiles.length}/><Metric i={<Store size={18}/>} l="Restorani" v={restaurants.length}/><Metric i={<TicketCheck size={18}/>} l="Aktivni paketi" v={active.length}/><Metric i={<WalletCards size={18}/>} l="Čeka uplatu" v={pending.length}/><Metric i={<CircleDollarSign size={18}/>} l="Ovaj mesec" v={`${monthRevenue.toFixed(0)} €`}/><Metric i={<BadgeEuro size={18}/>} l="Ukupno" v={`${revenue.toFixed(0)} €`}/></section>{expiring.length>0&&<section className="admin-alert-strip"><Bell size={18}/><div><strong>{expiring.length} paketa ističe u narednih 7 dana</strong><span>Podsetnici su pripremljeni u Outbox-u.</span></div><button onClick={()=>setView('customers')}>Kupci</button></section>}<div className="admin-overview-grid"><QuickSale profiles={profiles} plans={plans} form={sale} setForm={setSale} go={grant} working={working}/><LicenseMaker plans={plans} form={license} setForm={setLicense} go={makeLicense} generated={generated} copy={copy} working={working}/></div><section className="admin-panel"><Head e="POSLEDNJE NARUDŽBINE" t="Prodajni tok" side={<button className="secondary" onClick={exportCsv}><FileDown size={14}/> CSV</button>}/><Orders rows={orders.slice(0,8)} profiles={profiles} paid={paid} cancel={cancel} refund={refund} working={working}/></section></>}
 {view==='customers'&&<section className="admin-panel"><div className="admin-panel-head admin-customers-head"><div><p className="eyebrow">KUPCI</p><h2>Nalozi i pristup</h2></div><div className="admin-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Email, restoran, firma..."/></div></div><div className="admin-table customer-table customer-table-v2"><div className="admin-table-head"><span>Kupac</span><span>Restoran</span><span>Paket</span><span>Važi do</span><span>Kontrola</span></div>{customers.map(p=>{const s=subByUser.get(p.user_id),r=restByUser.get(p.user_id);return <div className="admin-table-row" key={p.user_id}><div><strong>{p.full_name||p.email}</strong><small>{p.email}{p.company?` · ${p.company}`:''}</small></div><div><strong>{r?.name||'—'}</strong><small>{r?.city||'nije dodat'}</small></div><div>{s?<><span className={`status ${s.status}`}>{s.status}</span><small>{s.sales_plans?.name||'custom'}</small></>:<span className="status pending">bez paketa</span>}</div><div><strong>{s?.expires_at?new Date(s.expires_at).toLocaleDateString('sr-RS'):s?'bez isteka':'—'}</strong>{s?.expires_at&&daysTo(s.expires_at)<=7&&daysTo(s.expires_at)>=0?<small className="expires-soon">još {daysTo(s.expires_at)} dana</small>:null}</div><div className="admin-row-actions"><button onClick={()=>{setNoteTarget(p);setNoteBody('')}}><Mail size={13}/> Poruka</button>{s&&<><button onClick={()=>void extend(s,30)}>+30d</button><button onClick={()=>void extend(s,365)}>+1g</button>{s.status==='suspended'?<button onClick={()=>void subStatus(s,'active')}><CheckCircle2 size={13}/> Aktiviraj</button>:<button className="danger-soft" onClick={()=>void subStatus(s,'suspended')}><Ban size={13}/> Suspenduj</button>}</>}</div></div>})}</div></section>}
 {view==='orders'&&<section className="admin-panel"><Head e="PRODAJA" t="Narudžbine, uplate i refundi" side={<div className="admin-head-actions"><span className="admin-counter">{pending.length} čeka</span><button className="secondary" onClick={exportCsv}><FileDown size={14}/> CSV</button></div>}/><Orders rows={orders} profiles={profiles} paid={paid} cancel={cancel} refund={refund} working={working}/></section>}
 {view==='licenses'&&<div className="admin-two-column"><LicenseMaker plans={plans} form={license} setForm={setLicense} go={makeLicense} generated={generated} copy={copy} working={working}/><section className="admin-panel"><Head e="IZDATE LICENCE" t="Kontrola kodova"/><div className="license-list">{licenses.length?licenses.map(x=><div className="license-row-admin" key={x.id}><div><strong>•••• {x.code_last4}</strong><span>{x.sales_plans?.name||'Paket'} · {x.assigned_email||'bez email ograničenja'}</span></div><div><span className={`status ${x.status}`}>{x.status}</span><small>{x.use_count}/{x.max_uses} · {x.sale_amount??0} {x.currency}</small></div>{x.status==='active'&&<button className="danger-soft" onClick={()=>void revoke(x)}>Opozovi</button>}</div>):<div className="admin-empty">Nema licenci.</div>}</div></section></div>}
 {view==='plans'&&<section className="admin-panel"><Head e="PAKETI I CENE" t="Komercijalni modeli"/><div className="plan-admin-grid">{plans.map(p=><Plan key={p.id} p={p} save={savePlan} toggle={togglePlan}/>)}</div></section>}
 {view==='outbox'&&<section className="admin-panel"><Head e="EMAIL / IN-APP OUTBOX" t="Sistemske poruke" side={<span className="admin-counter">{queued.length} čeka</span>}/><div className="outbox-list">{outbox.length?outbox.map(x=><div className={`outbox-row ${x.delivery_status}`} key={x.id}><div><strong>{x.subject}</strong><span>{x.recipient_email||'bez emaila'} · {new Date(x.created_at).toLocaleString('sr-RS')}</span><p>{x.body}</p></div><span className={`status ${x.delivery_status}`}>{x.delivery_status}</span><div className="admin-row-actions"><button onClick={()=>copy(`${x.subject}\n\n${x.body}`)}><Copy size={13}/> Kopiraj</button>{x.delivery_status==='queued'&&<><button onClick={()=>void markOut(x,'sent')}><CheckCircle2 size={13}/> Poslato</button><button className="danger-soft" onClick={()=>void markOut(x,'dismissed')}>Skloni</button></>}</div></div>):<div className="admin-empty">Outbox je prazan.</div>}</div></section>}
 {view==='audit'&&<section className="admin-panel"><Head e="AUDIT LOG" t="Istorija prodajnih akcija"/><div className="audit-list">{audit.length?audit.map(x=><div className="audit-row" key={x.id}><span className="audit-dot"/><div><strong>{auditLabel(x.action)}</strong><span>{x.entity_type}{x.entity_id?` · ${x.entity_id}`:''}</span></div><code>{compact(x.details)}</code><time>{new Date(x.created_at).toLocaleString('sr-RS')}</time></div>):<div className="admin-empty">Audit je prazan.</div>}</div></section>}
 {view==='settings'&&settings&&<section className="admin-panel admin-settings-panel"><Head e="PRODAJNA PODEŠAVANJA" t="Firma, banka i naplata"/><div className="admin-settings-sections"><SettingSection title="Identitet prodavca"><F l="Naziv u aplikaciji" v={settings.company_name} c={v=>setSettings({...settings,company_name:v})}/><F l="Pravni naziv" v={settings.legal_name||''} c={v=>setSettings({...settings,legal_name:v})}/><F l="PIB" v={settings.tax_id||''} c={v=>setSettings({...settings,tax_id:v})}/><F l="Matični broj" v={settings.company_number||''} c={v=>setSettings({...settings,company_number:v})}/><F l="Adresa" v={settings.address||''} c={v=>setSettings({...settings,address:v})}/><F l="Sales email" v={settings.sales_email||''} c={v=>setSettings({...settings,sales_email:v})}/><F l="Support email" v={settings.support_email||''} c={v=>setSettings({...settings,support_email:v})}/><F l="Uslovi korišćenja URL" v={settings.terms_url||''} c={v=>setSettings({...settings,terms_url:v})}/></SettingSection><SettingSection title="Banka / faktura"><F l="Banka" v={settings.bank_name||''} c={v=>setSettings({...settings,bank_name:v})}/><F l="Broj računa" v={settings.bank_account||''} c={v=>setSettings({...settings,bank_account:v})}/><F l="Model" v={settings.payment_model||''} c={v=>setSettings({...settings,payment_model:v})}/><label>Rok za uplatu<input type="number" min="1" max="30" value={settings.order_due_days||5} onChange={e=>setSettings({...settings,order_due_days:Number(e.target.value)})}/></label><label className="span-2">Instrukcije<textarea rows={4} value={settings.bank_instructions||''} onChange={e=>setSettings({...settings,bank_instructions:e.target.value})}/></label><label className="span-2">Napomena uz fakturu<textarea rows={3} value={settings.invoice_note||''} onChange={e=>setSettings({...settings,invoice_note:e.target.value})}/></label></SettingSection><SettingSection title="Kanali"><F l="PayPal payment link" v={settings.paypal_url||''} c={v=>setSettings({...settings,paypal_url:v})}/><label>Podsetnik pre isteka<input type="number" min="1" max="30" value={settings.renewal_notice_days||7} onChange={e=>setSettings({...settings,renewal_notice_days:Number(e.target.value)})}/></label><div className="sales-method-toggles span-2"><Toggle l="Uplata na račun" v={settings.allow_bank_transfer} c={v=>setSettings({...settings,allow_bank_transfer:v})}/><Toggle l="Faktura" v={settings.allow_invoice} c={v=>setSettings({...settings,allow_invoice:v})}/><Toggle l="PayPal" v={settings.allow_paypal} c={v=>setSettings({...settings,allow_paypal:v})}/><Toggle l="Kartica" v={settings.allow_card} c={v=>setSettings({...settings,allow_card:v})}/><Toggle l="Trial" v={settings.trial_enabled} c={v=>setSettings({...settings,trial_enabled:v})}/></div></SettingSection></div><button className="primary" onClick={saveSettings} disabled={working}><Save size={16}/> Sačuvaj prodajna podešavanja</button></section>}
 {noteTarget&&<div className="modal-backdrop" onMouseDown={()=>setNoteTarget(null)}><div className="modal-card admin-note-modal" onMouseDown={e=>e.stopPropagation()}><p className="eyebrow">PORUKA KUPCU</p><h2>{noteTarget.email}</h2><label>Naslov<input value={noteSubject} onChange={e=>setNoteSubject(e.target.value)}/></label><label>Poruka<textarea rows={6} value={noteBody} onChange={e=>setNoteBody(e.target.value)}/></label><div className="modal-actions"><button className="secondary" onClick={()=>setNoteTarget(null)}>Otkaži</button><button className="primary" onClick={sendNote} disabled={working}><Mail size={15}/> Dodaj poruku</button></div></div></div>}
 </div>
}
function Tab({a,f,i,l,c}:{a:boolean;f:()=>void;i:ReactNode;l:string;c?:number}){return <button className={a?'active':''} onClick={f}>{i}{l}{c?<b>{c}</b>:null}</button>}
function Metric({i,l,v}:{i:ReactNode;l:string;v:string|number}){return <div className="admin-metric"><span>{i}</span><div><small>{l}</small><strong>{v}</strong></div></div>}
function Head({e,t,side}:{e:string;t:string;side?:ReactNode}){return <div className="admin-panel-head"><div><p className="eyebrow">{e}</p><h2>{t}</h2></div>{side}</div>}
function QuickSale({profiles,plans,form,setForm,go,working}:{profiles:CustomerProfile[];plans:SalesPlan[];form:SaleForm;setForm:(v:SaleForm)=>void;go:()=>void;working:boolean}){return <section className="admin-panel"><Head e="BRZA PRODAJA" t="Aktiviraj kupca odmah"/><div className="admin-form-grid"><label>Kupac<select value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}><option value="">Izaberi</option>{profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.email}</option>)}</select></label><label>Paket<select value={form.planId} onChange={e=>setForm({...form,planId:e.target.value})}><option value="">Izaberi</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name} · {p.price} {p.currency}</option>)}</select></label><label>Dana<input type="number" min="1" value={form.days} onChange={e=>setForm({...form,days:e.target.value})}/></label><label>Naplaćeno<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Način<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{methods.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Napomena<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button className="primary full" onClick={go} disabled={working}><CheckCircle2 size={16}/> Aktiviraj i evidentiraj</button></section>}
function LicenseMaker({plans,form,setForm,go,generated,copy,working}:{plans:SalesPlan[];form:LicenseForm;setForm:(v:LicenseForm)=>void;go:()=>void;generated:Generated|null;copy:(v:string)=>void;working:boolean}){return <section className="admin-panel"><Head e="AKTIVACIONI KOD" t="Prodaj licencu"/><div className="admin-form-grid"><label>Paket<select value={form.planId} onChange={e=>setForm({...form,planId:e.target.value})}><option value="">Izaberi</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Dana<input type="number" min="1" value={form.days} onChange={e=>setForm({...form,days:e.target.value})}/></label><label>Cena<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Način<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{methods.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Napomena<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button className="primary full" onClick={go} disabled={working}><KeyRound size={16}/> Generiši licencu</button>{generated&&<div className="generated-license"><span>KOPIRAJ SADA</span><strong>{generated.code}</strong><small>{generated.plan}</small><button onClick={()=>copy(generated.code)}><Copy size={15}/> Kopiraj</button></div>}</section>}
function Orders({rows,profiles,paid,cancel,refund,working}:{rows:SalesOrder[];profiles:CustomerProfile[];paid:(o:SalesOrder)=>void;cancel:(o:SalesOrder)=>void;refund:(o:SalesOrder)=>void;working:boolean}){const m=new Map(profiles.map(p=>[p.user_id,p]));return <div className="admin-table orders-table orders-table-v2"><div className="admin-table-head"><span>Narudžbina</span><span>Kupac</span><span>Paket</span><span>Iznos</span><span>Status</span><span>Akcija</span></div>{rows.length?rows.map(o=><div className="admin-table-row" key={o.id}><div><strong>{o.order_number}</strong><small>{new Date(o.created_at).toLocaleString('sr-RS')} · {o.payment_reference||o.order_number}</small></div><div><strong>{m.get(o.user_id)?.email||'Kupac'}</strong><small>{o.payment_method}</small></div><div><strong>{o.sales_plans?.name||'—'}</strong><small>{o.due_at?`rok ${new Date(o.due_at).toLocaleDateString('sr-RS')}`:''}</small></div><strong>{o.amount} {o.currency}</strong><span className={`status ${o.status}`}>{o.status}</span><div className="order-admin-actions">{o.status==='pending'&&<><button className="paid-button" disabled={working} onClick={()=>paid(o)}>Uplata primljena</button><button className="danger-soft" onClick={()=>cancel(o)}>Otkaži</button></>}{o.status==='paid'&&<button className="refund-button" onClick={()=>refund(o)}><Undo2 size={13}/> Refund</button>}</div></div>):<div className="admin-empty">Nema narudžbina.</div>}</div>}
function Plan({p,save,toggle}:{p:SalesPlan;save:(p:SalesPlan,price:number,limit:number,max:number)=>void;toggle:(p:SalesPlan)=>void}){const[price,setPrice]=useState(Number(p.price)),[limit,setLimit]=useState(p.monthly_generation_limit),[max,setMax]=useState(p.max_restaurants);useEffect(()=>{setPrice(Number(p.price));setLimit(p.monthly_generation_limit);setMax(p.max_restaurants)},[p.price,p.monthly_generation_limit,p.max_restaurants]);return <article className={`admin-plan ${p.active?'':'plan-disabled'}`}><div><span>{p.billing_interval}</span><b>{p.code}</b></div><h3>{p.name}</h3><p>{p.description}</p><div className="plan-edit-grid"><label>Cena<input type="number" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label><label>Objave/mes<input type="number" value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><label>Restorani<input type="number" min="1" value={max} onChange={e=>setMax(Number(e.target.value))}/></label></div><div className="admin-row-actions"><button onClick={()=>save(p,price,limit,max)}><Save size={13}/> Sačuvaj</button><button className={p.active?'danger-soft':''} onClick={()=>toggle(p)}>{p.active?'Isključi':'Uključi'}</button></div></article>}
function SettingSection({title,children}:{title:string;children:ReactNode}){return <div><h3>{title}</h3><div className="admin-form-grid">{children}</div></div>}
function F({l,v,c}:{l:string;v:string;c:(v:string)=>void}){return <label>{l}<input value={v} onChange={e=>c(e.target.value)}/></label>}
function Toggle({l,v,c}:{l:string;v:boolean;c:(v:boolean)=>void}){return <label className={`sales-toggle ${v?'on':''}`}><input type="checkbox" checked={v} onChange={e=>c(e.target.checked)}/><span/><b>{l}</b></label>}
function daysTo(v:string){return Math.ceil((new Date(v).getTime()-Date.now())/86400000)}
function auditLabel(v:string){return({order_paid:'Uplata potvrđena',order_refunded:'Refund',access_granted:'Ručna aktivacija',license_created:'Licenca kreirana',license_redeemed:'Licenca aktivirana',trial_started:'Trial',customer_note_queued:'Poruka kupcu',housekeeping:'Housekeeping'} as Record<string,string>)[v]||v}
function compact(v:Record<string,unknown>){const s=JSON.stringify(v);return s.length>120?`${s.slice(0,117)}…`:s}
function downloadCsv(name:string,rows:string[][]){const q=(v:string)=>`"${v.replaceAll('"','""')}"`;const csv='\ufeff'+rows.map(r=>r.map(q).join(';')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
