import { type ReactNode, useEffect, useMemo, useState } from 'react'
import { BadgeEuro, Ban, Banknote, CheckCircle2, Copy, CreditCard, KeyRound, RefreshCw, Save, Search, Settings2, ShieldCheck, Sparkles, Store, TicketCheck, UsersRound, WalletCards, Zap } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { CustomerProfile, CustomerSubscription, LicenseCodeRow, SalesOrder, SalesPlan, SalesSettings } from '../types'

type View = 'overview' | 'customers' | 'orders' | 'licenses' | 'plans' | 'settings'
type RestaurantLite = { id:string; owner_id:string; name:string; city:string|null; created_at:string }
type SaleForm = { userId:string; planId:string; days:string; amount:string; paymentMethod:string; note:string }
type LicenseForm = { planId:string; email:string; days:string; amount:string; paymentMethod:string; note:string }
type GeneratedLicense = { id:string; code:string; plan:string; assigned_email:string|null }

const methods = [
  ['manual','Ručno / ostalo'],['bank_transfer','Uplata na račun'],['invoice','Predračun / faktura'],['paypal','PayPal'],['card','Kartica'],['cash','Keš'],
] as const

export function SuperAdmin({ onCloseApp, setNotice }: { onCloseApp?:()=>void; setNotice:(value:string)=>void }) {
  const [view,setView] = useState<View>('overview')
  const [profiles,setProfiles] = useState<CustomerProfile[]>([])
  const [restaurants,setRestaurants] = useState<RestaurantLite[]>([])
  const [plans,setPlans] = useState<SalesPlan[]>([])
  const [subs,setSubs] = useState<CustomerSubscription[]>([])
  const [orders,setOrders] = useState<SalesOrder[]>([])
  const [licenses,setLicenses] = useState<LicenseCodeRow[]>([])
  const [settings,setSettings] = useState<SalesSettings|null>(null)
  const [working,setWorking] = useState(false)
  const [search,setSearch] = useState('')
  const [generated,setGenerated] = useState<GeneratedLicense|null>(null)
  const [sale,setSale] = useState<SaleForm>({userId:'',planId:'',days:'',amount:'',paymentMethod:'manual',note:''})
  const [license,setLicense] = useState<LicenseForm>({planId:'',email:'',days:'',amount:'',paymentMethod:'manual',note:''})

  useEffect(()=>{ void load() },[])

  async function load(){
    setWorking(true)
    const [a,b,c,d,e,f,g] = await Promise.all([
      supabase.from('customer_profiles').select('*').order('created_at',{ascending:false}),
      supabase.from('restaurants').select('id,owner_id,name,city,created_at').order('created_at',{ascending:false}),
      supabase.from('sales_plans').select('*').order('sort_order'),
      supabase.from('customer_subscriptions').select('*, sales_plans(*)').order('created_at',{ascending:false}),
      supabase.from('sales_orders').select('*, sales_plans(*)').order('created_at',{ascending:false}),
      supabase.from('license_codes').select('*, sales_plans(*)').order('created_at',{ascending:false}).limit(100),
      supabase.from('sales_settings').select('*').eq('id',1).maybeSingle(),
    ])
    const err=a.error||b.error||c.error||d.error||e.error||f.error||g.error
    if(err) setNotice(err.message)
    setProfiles((a.data||[]) as CustomerProfile[]); setRestaurants((b.data||[]) as RestaurantLite[])
    setPlans((c.data||[]) as SalesPlan[]); setSubs((d.data||[]) as CustomerSubscription[])
    setOrders((e.data||[]) as SalesOrder[]); setLicenses((f.data||[]) as LicenseCodeRow[])
    setSettings((g.data||null) as SalesSettings|null); setWorking(false)
  }

  const activeSubs=useMemo(()=>subs.filter(s=>['active','trialing'].includes(s.status)&&(!s.expires_at||new Date(s.expires_at)>new Date())),[subs])
  const pending=useMemo(()=>orders.filter(o=>o.status==='pending'),[orders])
  const revenue=useMemo(()=>orders.filter(o=>o.status==='paid').reduce((sum,o)=>sum+Number(o.amount||0),0),[orders])
  const subByUser=useMemo(()=>{const m=new Map<string,CustomerSubscription>();subs.forEach(s=>{if(!m.has(s.user_id))m.set(s.user_id,s)});return m},[subs])
  const restaurantByUser=useMemo(()=>{const m=new Map<string,RestaurantLite>();restaurants.forEach(r=>{if(!m.has(r.owner_id))m.set(r.owner_id,r)});return m},[restaurants])
  const customers=useMemo(()=>{const q=search.toLowerCase().trim();return !q?profiles:profiles.filter(p=>`${p.email} ${p.full_name||''} ${p.company||''} ${restaurantByUser.get(p.user_id)?.name||''}`.toLowerCase().includes(q))},[profiles,search,restaurantByUser])

  async function markPaid(order:SalesOrder){ setWorking(true); const {error}=await supabase.rpc('admin_mark_order_paid',{p_order_id:order.id,p_admin_note:'Potvrđeno iz Superadmin panela'}); if(error)setNotice(error.message);else{setNotice(`${order.order_number}: uplata potvrđena, pristup aktiviran.`);await load()} setWorking(false) }
  async function cancelOrder(order:SalesOrder){ if(!confirm(`Otkaži ${order.order_number}?`))return; const {error}=await supabase.from('sales_orders').update({status:'cancelled',admin_note:'Otkazano iz Superadmin panela'}).eq('id',order.id); if(error)setNotice(error.message);else{setNotice('Narudžbina je otkazana.');await load()} }
  async function grant(){ if(!sale.userId||!sale.planId){setNotice('Izaberi kupca i paket.');return} setWorking(true);const {error}=await supabase.rpc('admin_grant_access',{p_user_id:sale.userId,p_plan_id:sale.planId,p_days:sale.days?Number(sale.days):null,p_payment_method:sale.paymentMethod,p_amount:sale.amount?Number(sale.amount):null,p_note:sale.note||null});if(error)setNotice(error.message);else{setNotice('Prodaja evidentirana i kupac je odmah aktiviran.');setSale({userId:'',planId:'',days:'',amount:'',paymentMethod:'manual',note:''});await load()}setWorking(false) }
  async function makeLicense(){ if(!license.planId){setNotice('Izaberi paket.');return} setWorking(true);const {data,error}=await supabase.rpc('admin_create_license_code',{p_plan_id:license.planId,p_duration_days:license.days?Number(license.days):null,p_assigned_email:license.email||null,p_sale_amount:license.amount?Number(license.amount):null,p_payment_method:license.paymentMethod,p_note:license.note||null});if(error)setNotice(error.message);else{setGenerated(data as GeneratedLicense);setNotice('Licenca je napravljena. Kopiraj kod — puni kod se posle ne čuva u bazi.');await load()}setWorking(false) }
  async function setSubStatus(sub:CustomerSubscription,status:CustomerSubscription['status']){const {error}=await supabase.from('customer_subscriptions').update({status}).eq('id',sub.id);if(error)setNotice(error.message);else{setNotice(status==='suspended'?'Pristup je suspendovan.':'Pristup je aktiviran.');await load()} }
  async function extend(sub:CustomerSubscription,days=30){const d=sub.expires_at&&new Date(sub.expires_at)>new Date()?new Date(sub.expires_at):new Date();d.setDate(d.getDate()+days);const {error}=await supabase.from('customer_subscriptions').update({expires_at:d.toISOString(),status:'active'}).eq('id',sub.id);if(error)setNotice(error.message);else{setNotice(`Produženo za ${days} dana.`);await load()} }
  async function savePlan(plan:SalesPlan,price:number,limit:number){const {error}=await supabase.from('sales_plans').update({price,monthly_generation_limit:limit}).eq('id',plan.id);if(error)setNotice(error.message);else{setNotice(`${plan.name} je sačuvan.`);await load()} }
  async function togglePlan(plan:SalesPlan){const {error}=await supabase.from('sales_plans').update({active:!plan.active}).eq('id',plan.id);if(error)setNotice(error.message);else await load() }
  async function revoke(row:LicenseCodeRow){const {error}=await supabase.from('license_codes').update({status:'revoked'}).eq('id',row.id);if(error)setNotice(error.message);else{setNotice(`Licenca ••••${row.code_last4} je opozvana.`);await load()} }
  async function saveSettings(){if(!settings)return;setWorking(true);const {error}=await supabase.from('sales_settings').update(settings).eq('id',1);if(error)setNotice(error.message);else setNotice('Načini prodaje su sačuvani.');setWorking(false)}
  function copy(value:string){navigator.clipboard.writeText(value).then(()=>setNotice('Kopirano.')).catch(()=>setNotice('Browser nije dozvolio kopiranje.'))}

  return <div className="superadmin-page">
    <header className="admin-topbar"><div><span className="admin-shield"><ShieldCheck size={21}/></span><div><p>RESTAURANT AUTOPILOT</p><h1>Superadmin</h1></div></div><div className="admin-top-actions"><span className="admin-live"><i/> OWNER CONTROL</span><button className="secondary" onClick={()=>void load()} disabled={working}><RefreshCw size={15}/> Osveži</button>{onCloseApp&&<button className="secondary" onClick={onCloseApp}>Nazad u app</button>}</div></header>
    <nav className="admin-tabs"><Tab active={view==='overview'} onClick={()=>setView('overview')} icon={<Zap size={16}/>} label="Pregled"/><Tab active={view==='customers'} onClick={()=>setView('customers')} icon={<UsersRound size={16}/>} label="Kupci"/><Tab active={view==='orders'} onClick={()=>setView('orders')} icon={<WalletCards size={16}/>} label="Prodaja" count={pending.length}/><Tab active={view==='licenses'} onClick={()=>setView('licenses')} icon={<KeyRound size={16}/>} label="Licence"/><Tab active={view==='plans'} onClick={()=>setView('plans')} icon={<BadgeEuro size={16}/>} label="Paketi"/><Tab active={view==='settings'} onClick={()=>setView('settings')} icon={<Settings2 size={16}/>} label="Podešavanja"/></nav>

    {view==='overview'&&<><section className="admin-metrics"><Metric icon={<UsersRound size={18}/>} label="Registrovani" value={profiles.length}/><Metric icon={<Store size={18}/>} label="Restorani" value={restaurants.length}/><Metric icon={<TicketCheck size={18}/>} label="Aktivni paketi" value={activeSubs.length}/><Metric icon={<WalletCards size={18}/>} label="Čeka uplatu" value={pending.length}/><Metric icon={<BadgeEuro size={18}/>} label="Evidentirano" value={`${revenue.toFixed(0)} €`}/></section><div className="admin-overview-grid"><QuickSale profiles={profiles} plans={plans} form={sale} setForm={setSale} onSubmit={grant} working={working}/><LicenseMaker plans={plans} form={license} setForm={setLicense} onSubmit={makeLicense} generated={generated} onCopy={copy} working={working}/></div><section className="admin-panel"><PanelTitle eyebrow="POSLEDNJE NARUDŽBINE" title="Prodajni tok" icon={<WalletCards size={21}/>}/><OrdersTable orders={orders.slice(0,8)} profiles={profiles} onPaid={markPaid} onCancel={cancelOrder} working={working}/></section></>}

    {view==='customers'&&<section className="admin-panel"><div className="admin-panel-head admin-customers-head"><div><p className="eyebrow">KUPCI</p><h2>Nalozi i pristup</h2></div><div className="admin-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Email, restoran, firma..."/></div></div><div className="admin-table customer-table"><div className="admin-table-head"><span>Kupac</span><span>Restoran</span><span>Paket</span><span>Važi do</span><span>Kontrola</span></div>{customers.map(p=>{const sub=subByUser.get(p.user_id),r=restaurantByUser.get(p.user_id);return <div className="admin-table-row" key={p.user_id}><div><strong>{p.full_name||p.email}</strong><small>{p.email}</small></div><div><strong>{r?.name||'—'}</strong><small>{r?.city||'nije dodat'}</small></div><div>{sub?<><span className={`status ${sub.status}`}>{sub.status}</span><small>{sub.sales_plans?.name||'custom'}</small></>:<span className="status pending">bez paketa</span>}</div><div><strong>{sub?.expires_at?new Date(sub.expires_at).toLocaleDateString('sr-RS'):sub?'bez isteka':'—'}</strong></div><div className="admin-row-actions">{sub&&<><button onClick={()=>void extend(sub)}>+30d</button>{sub.status==='suspended'?<button onClick={()=>void setSubStatus(sub,'active')}><CheckCircle2 size={13}/> Aktiviraj</button>:<button className="danger-soft" onClick={()=>void setSubStatus(sub,'suspended')}><Ban size={13}/> Suspenduj</button>}</>}</div></div>})}</div></section>}

    {view==='orders'&&<section className="admin-panel"><PanelTitle eyebrow="PRODAJA" title="Narudžbine i uplate" icon={<WalletCards size={21}/>} side={<span className="admin-counter">{pending.length} čeka potvrdu</span>}/><OrdersTable orders={orders} profiles={profiles} onPaid={markPaid} onCancel={cancelOrder} working={working}/></section>}

    {view==='licenses'&&<div className="admin-two-column"><LicenseMaker plans={plans} form={license} setForm={setLicense} onSubmit={makeLicense} generated={generated} onCopy={copy} working={working}/><section className="admin-panel"><PanelTitle eyebrow="IZDATE LICENCE" title="Kontrola kodova"/><div className="license-list">{licenses.map(row=><div className="license-row-admin" key={row.id}><div><strong>•••• {row.code_last4}</strong><span>{row.sales_plans?.name||'Paket'} · {row.assigned_email||'bez email ograničenja'}</span></div><div><span className={`status ${row.status}`}>{row.status}</span><small>{row.use_count}/{row.max_uses} korišćenja</small></div>{row.status==='active'&&<button className="danger-soft" onClick={()=>void revoke(row)}>Opozovi</button>}</div>)}</div></section></div>}

    {view==='plans'&&<section className="admin-panel"><PanelTitle eyebrow="PAKETI I CENE" title="Cene menjaš bez izmene programa" icon={<BadgeEuro size={21}/>}/><div className="plan-admin-grid">{plans.map(plan=><PlanCard key={plan.id} plan={plan} onSave={savePlan} onToggle={togglePlan}/>)}</div><div className="admin-tip"><Zap size={16}/><span>Podržani su mesečni, godišnji, custom i lifetime modeli. Lifetime nije javno uključen jer SaaS ima stalne troškove; možeš ga kasnije ponuditi kao ograničen Founders paket.</span></div></section>}

    {view==='settings'&&settings&&<section className="admin-panel admin-settings-panel"><PanelTitle eyebrow="PRODAJNA PODEŠAVANJA" title="Načini prodaje" icon={<Settings2 size={21}/>}/><div className="admin-form-grid"><label>Naziv prodavca<input value={settings.company_name} onChange={e=>setSettings({...settings,company_name:e.target.value})}/></label><label>Sales email<input value={settings.sales_email||''} onChange={e=>setSettings({...settings,sales_email:e.target.value})}/></label><label>Support email<input value={settings.support_email||''} onChange={e=>setSettings({...settings,support_email:e.target.value})}/></label><label>PayPal link<input value={settings.paypal_url||''} onChange={e=>setSettings({...settings,paypal_url:e.target.value})} placeholder="https://..."/></label><label className="span-2">Podaci za uplatu<textarea rows={5} value={settings.bank_instructions||''} onChange={e=>setSettings({...settings,bank_instructions:e.target.value})} placeholder={'Primalac:\nRačun / IBAN:\nSWIFT:\nPoziv na broj:'}/></label></div><div className="payment-toggles"><PayToggle icon={<Banknote size={17}/>} label="Uplata na račun" value={settings.allow_bank_transfer} set={v=>setSettings({...settings,allow_bank_transfer:v})}/><PayToggle icon={<WalletCards size={17}/>} label="Predračun" value={settings.allow_invoice} set={v=>setSettings({...settings,allow_invoice:v})}/><PayToggle icon={<CreditCard size={17}/>} label="PayPal" value={settings.allow_paypal} set={v=>setSettings({...settings,allow_paypal:v})}/><PayToggle icon={<CreditCard size={17}/>} label="Kartica" value={settings.allow_card} set={v=>setSettings({...settings,allow_card:v})}/><PayToggle icon={<Sparkles size={17}/>} label="Trial" value={settings.trial_enabled} set={v=>setSettings({...settings,trial_enabled:v})}/></div><button className="primary" onClick={()=>void saveSettings()} disabled={working}><Save size={16}/> Sačuvaj prodaju</button></section>}
  </div>
}

function Tab({active,onClick,icon,label,count=0}:{active:boolean;onClick:()=>void;icon:ReactNode;label:string;count?:number}){return <button className={active?'active':''} onClick={onClick}>{icon}{label}{count>0&&<b>{count}</b>}</button>}
function Metric({icon,label,value}:{icon:ReactNode;label:string;value:string|number}){return <div className="admin-metric"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function PanelTitle({eyebrow,title,icon,side}:{eyebrow:string;title:string;icon?:ReactNode;side?:ReactNode}){return <div className="admin-panel-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{side||icon}</div>}

function QuickSale({profiles,plans,form,setForm,onSubmit,working}:{profiles:CustomerProfile[];plans:SalesPlan[];form:SaleForm;setForm:(v:SaleForm)=>void;onSubmit:()=>void;working:boolean}){return <section className="admin-panel"><PanelTitle eyebrow="BRZA PRODAJA" title="Aktiviraj kupca odmah" icon={<TicketCheck size={21}/>}/><p className="muted">Kupac prvo napravi nalog, a ti mu ovde za 10 sekundi aktiviraš paket i evidentiraš način uplate.</p><div className="admin-form-grid"><label>Kupac<select value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}><option value="">Izaberi kupca</option>{profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.email}</option>)}</select></label><label>Paket<select value={form.planId} onChange={e=>setForm({...form,planId:e.target.value})}><option value="">Izaberi paket</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name} · {p.price} {p.currency}</option>)}</select></label><label>Trajanje dana<input type="number" min="1" value={form.days} onChange={e=>setForm({...form,days:e.target.value})} placeholder="prazno = paket"/></label><label>Naplaćeno<input type="number" min="0" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="prazno = cena paketa"/></label><label>Način<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{methods.map(m=><option value={m[0]} key={m[0]}>{m[1]}</option>)}</select></label><label>Napomena<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button className="primary full" onClick={onSubmit} disabled={working}><CheckCircle2 size={16}/> Aktiviraj i evidentiraj prodaju</button></section>}

function LicenseMaker({plans,form,setForm,onSubmit,generated,onCopy,working}:{plans:SalesPlan[];form:LicenseForm;setForm:(v:LicenseForm)=>void;onSubmit:()=>void;generated:GeneratedLicense|null;onCopy:(v:string)=>void;working:boolean}){return <section className="admin-panel"><PanelTitle eyebrow="AKTIVACIONI KOD" title="Prodaj licencu" icon={<KeyRound size={21}/>}/><div className="admin-form-grid"><label>Paket<select value={form.planId} onChange={e=>setForm({...form,planId:e.target.value})}><option value="">Izaberi paket</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name} · {p.price} {p.currency}</option>)}</select></label><label>Veži za email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="opciono"/></label><label>Trajanje dana<input type="number" min="1" value={form.days} onChange={e=>setForm({...form,days:e.target.value})} placeholder="prazno = paket"/></label><label>Prodajna cena<input type="number" min="0" step=".01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Način<select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value})}>{methods.map(m=><option value={m[0]} key={m[0]}>{m[1]}</option>)}</select></label><label>Napomena<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button className="primary full" onClick={onSubmit} disabled={working}><KeyRound size={16}/> Generiši licencu</button>{generated&&<div className="generated-license"><span>KOPIRAJ SADA</span><strong>{generated.code}</strong><small>{generated.plan}{generated.assigned_email?` · ${generated.assigned_email}`:''}</small><button onClick={()=>onCopy(generated.code)}><Copy size={15}/> Kopiraj kod</button></div>}</section>}

function OrdersTable({orders,profiles,onPaid,onCancel,working}:{orders:SalesOrder[];profiles:CustomerProfile[];onPaid:(o:SalesOrder)=>void;onCancel:(o:SalesOrder)=>void;working:boolean}){const mail=(id:string)=>profiles.find(p=>p.user_id===id)?.email||id.slice(0,8);return <div className="admin-table orders-table"><div className="admin-table-head"><span>Broj</span><span>Kupac</span><span>Paket</span><span>Iznos</span><span>Način</span><span>Status / akcija</span></div>{orders.length===0?<div className="admin-empty">Još nema narudžbina.</div>:orders.map(o=><div className="admin-table-row" key={o.id}><div><strong>{o.order_number}</strong><small>{new Date(o.created_at).toLocaleString('sr-RS',{dateStyle:'short',timeStyle:'short'})}</small></div><div><strong>{mail(o.user_id)}</strong></div><div><strong>{o.sales_plans?.name||'Paket'}</strong></div><div><strong>{Number(o.amount).toFixed(0)} {o.currency}</strong></div><div><span>{methods.find(m=>m[0]===o.payment_method)?.[1]||o.payment_method}</span></div><div className="order-admin-actions"><span className={`status ${o.status}`}>{o.status}</span>{o.status==='pending'&&<><button className="paid-button" disabled={working} onClick={()=>onPaid(o)}><CheckCircle2 size={13}/> Uplata primljena</button><button className="danger-soft" onClick={()=>onCancel(o)}>Otkaži</button></>}</div></div>)}</div>}

function PlanCard({plan,onSave,onToggle}:{plan:SalesPlan;onSave:(p:SalesPlan,price:number,limit:number)=>void;onToggle:(p:SalesPlan)=>void}){const [price,setPrice]=useState(String(plan.price));const [limit,setLimit]=useState(String(plan.monthly_generation_limit));return <article className={`admin-plan ${plan.active?'':'inactive'}`}><div><span className="plan-code">{plan.code}</span><h3>{plan.name}</h3><p>{plan.billing_interval}</p></div><label>Cena<div className="price-admin-input"><input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)}/><b>{plan.currency}</b></div></label><label>Limit generacija<input type="number" min="0" value={limit} onChange={e=>setLimit(e.target.value)}/></label><div className="admin-plan-actions"><button className={`toggle-active ${plan.active?'active':''}`} onClick={()=>onToggle(plan)}>{plan.active?'Aktivan':'Isključen'}</button><button className="primary" onClick={()=>onSave(plan,Number(price),Number(limit))}><Save size={13}/> Sačuvaj</button></div></article>}
function PayToggle({icon,label,value,set}:{icon:ReactNode;label:string;value:boolean;set:(v:boolean)=>void}){return <button type="button" className={`payment-toggle ${value?'active':''}`} onClick={()=>set(!value)}>{icon}<span>{label}</span><b>{value?'UKLJUČENO':'ISKLJUČENO'}</b></button>}
